import { ContactSection } from "@/components/ContactSection";
import { amsterdamServices, amsterdamPages } from "@/data/amsterdam";
import { PageLayout, Section, ActionLink, FAQ } from "@/components/PageLayout";
import NotFound from "./not-found";
export function AmsterdamServicePage({ slug, audience }: { slug: string; audience: "opdrachtgever" | "kandidaat" }) {
  const service = amsterdamServices.find(item => item.slug === slug);
  const page = amsterdamPages.find(item => item.slug === slug && item.audience === audience);
  if (!service || !page) return <NotFound />;
  const isProfessional = audience === "kandidaat";
  const contactHref = "#contact";
  const candidateSteps: Record<string, string[][]> = {
    "werving-selectie-amsterdam": [["Welke rol zoek je?", "Vertel wat voor werk je zoekt, wat je graag wilt oppakken en hoeveel uur je wilt werken. Zo kunnen we beoordelen of een vaste functie bij jouw wensen aansluit."], ["De functie bespreken", "Voor een mogelijke introductie bespreken we eerst de functie, organisatie, arbeidsvoorwaarden en jouw interesse. Je komt bij werving & selectie rechtstreeks in dienst bij de opdrachtgever."]],
    "detachering-amsterdam": [["De opdracht begrijpen", "We bespreken wat de opdrachtgever nodig heeft, wie jouw aanspreekpunt wordt en hoe jouw ervaring aansluit op het team."], ["Weten waar je aan toe bent", "Vóór een mogelijke start bespreken we jouw arbeidsovereenkomst, arbeidsvoorwaarden en de afspraken over de inzet bij de opdrachtgever."]],
    "interim-amsterdam": [["Vertel welk werk je zoekt", "Noem het soort opdracht dat bij je past, hoeveel dagen je beschikbaar bent en wanneer je weer ruimte hebt."], ["De opdracht afstemmen", "We bespreken het resultaat, de looptijd, verantwoordelijkheden en voorwaarden. We stellen je alleen voor na overleg met jou."]],
    "detavast-amsterdam": [["Beide fases bespreken", "We kijken naar de start via Wedeploy én naar de functie bij de opdrachtgever daarna. Jouw wensen voor de langere termijn horen vanaf het begin bij het gesprek."], ["Een bewuste vervolgstap", "Je hoort vooraf welke periode en voorwaarden worden voorgesteld. We bespreken hoe de samenwerking wordt geëvalueerd en wat de beoogde overstap inhoudt."]],
  };
  const steps = isProfessional ? candidateSteps[slug] : service.details;
  const candidateHeadings: Record<string, string> = { "werving-selectie-amsterdam": "Rechtstreeks in dienst.", "detachering-amsterdam": "Zo werkt detachering.", "interim-amsterdam": "Jouw inzet als zelfstandige.", "detavast-amsterdam": "De route naar vaste dienst." };
  const employerHeadings: Record<string, string> = { "werving-selectie-amsterdam": "Een vaste collega.", "detachering-amsterdam": "Tijdelijke versterking.", "interim-amsterdam": "Expertise voor jouw opdracht.", "detavast-amsterdam": "Een collega voor de toekomst." };
  const cityCopy: Record<string, { employer: string; candidate: string }> = {
    "werving-selectie-amsterdam": { employer: "Voor vaste functies in Amsterdam bespreken we eerst de rol, het team en de arbeidsvoorwaarden. Daarna zoeken we iemand die rechtstreeks bij jouw organisatie in dienst kan komen.", candidate: "Zoek je een vaste functie in Amsterdam? Vertel wat voor rol je zoekt en welke taken je graag wilt oppakken. We bespreken jouw wensen voordat we je eventueel introduceren." },
    "detachering-amsterdam": { employer: "Bij detachering werkt de professional tijdelijk binnen jouw organisatie in Amsterdam en is diegene in dienst bij Wedeploy. We stemmen taken, uren, startdatum en begeleiding vooraf af.", candidate: "Zoek je een functie via detachering in Amsterdam? We bespreken de werkzaamheden, uren en arbeidsvoorwaarden voordat je beslist of de opdracht bij je past." },
    "interim-amsterdam": { employer: "Voor een interim-opdracht in Amsterdam brengen we het gewenste resultaat, de looptijd en benodigde inzet in kaart. Daarna bespreken we welke zelfstandige expertise daarbij past.", candidate: "Als zelfstandig professional kun je aangeven welke interim-opdracht je zoekt en wanneer je beschikbaar bent. We bespreken een mogelijke opdracht en de voorwaarden eerst met jou." },
    "detavast-amsterdam": { employer: "Bij detavast werkt de professional eerst via Wedeploy, met de bedoeling later bij jouw organisatie in dienst te komen. We spreken de periode en voorwaarden vooraf af.", candidate: "Zoek je in Amsterdam een functie met detavast als mogelijke route? We bespreken de start via Wedeploy én de voorwaarden voor een mogelijke overstap. Die overstap is geen garantie." },
  };
  const hero = slug === "detachering-amsterdam" ? "graphic" : slug === "detavast-amsterdam" ? "paper" : isProfessional && slug === "werving-selectie-amsterdam" ? "paper" : !isProfessional && slug === "werving-selectie-amsterdam" ? "line" : "type";
  const variant = slug === "detavast-amsterdam" ? "quiet" : slug === "interim-amsterdam" ? "navy" : isProfessional ? "editorial" : "split";
  return <PageLayout variant={variant} hero={hero} label={page.label} title={isProfessional ? service.professionalTitle : employerHeadings[slug]} intro={isProfessional ? service.professionalText : service.employerText} cta={isProfessional ? "Stuur jouw cv" : "Bespreek jouw vraag"} ctaHref={contactHref} secondary={{ label: isProfessional ? "Vacatures & opdrachten" : "Bekijk ons netwerk", href: isProfessional ? "/vacatures" : "/professionals" }}>
    <Section tone={isProfessional ? "white" : "plain"}><div className={isProfessional ? "candidate-story" : "grid md:grid-cols-[.85fr_1.15fr] gap-8 md:gap-16"}><div><p className="eyebrow">{isProfessional ? "Voor professionals" : "Voor opdrachtgevers"}</p><h2 className="section-title">{isProfessional ? candidateHeadings[slug] : "Van vraag naar zoekprofiel."}</h2><p className="mt-5 text-muted-foreground leading-relaxed">{isProfessional ? service.professionalNote : "Wat moet iemand oppakken? We bespreken de verantwoordelijkheden, de werkomgeving en de gewenste ervaring. Daarop bouwen we de zoektocht."}</p></div><div>{steps.map(([title, text]) => <article key={title} className="editorial-item"><h3 className="text-xl font-bold text-primary">{title}</h3><p className="mt-4 text-muted-foreground leading-relaxed">{text}</p></article>)}</div></div></Section>
    <Section tone="wash"><div className="sector-statement"><div><p className="eyebrow">Projectmanagement, vastgoed, Facility Management en meer</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">{isProfessional ? "De rol die bij je past." : "Wie past bij het werk?"}</h2></div><div><p className="text-muted-foreground leading-relaxed">{isProfessional ? cityCopy[slug].candidate : cityCopy[slug].employer}</p><div className="mt-7"><ActionLink href={contactHref}>{isProfessional ? "Vertel wat je zoekt" : "Bespreek jouw personeelsvraag"}</ActionLink></div></div></div></Section>
    <Section><div className="grid md:grid-cols-2 gap-8 md:gap-16"><div><p className="eyebrow">Vanuit Amsterdam, landelijk actief</p><h2 className="section-title">Duidelijk over de werkplek.</h2></div><div className="space-y-4 text-muted-foreground leading-relaxed"><p>Wedeploy is gevestigd op IJburg en bemiddelt in heel Nederland. Voor een opdracht in Amsterdam stemmen we de locatie, werkdagen en aanwezigheid vooraf af.</p><p>{isProfessional ? "Zo weet je waar en hoeveel uur je werkt en kun je beoordelen of de functie of opdracht bij je past." : "Zo kunnen we kandidaten vooraf een helder beeld geven van de werklocatie en praktische afspraken."}</p></div></div></Section>
    <FAQ items={isProfessional ? [{ question: "Staat er nu een vacature open?", answer: "Op de website publiceren we alleen concrete vacatures als die beschikbaar zijn. Je kunt ook je cv insturen zonder op een vacature te reageren. We nemen contact op als een passende mogelijkheid ontstaat." }, { question: "Wordt mijn cv doorgestuurd?", answer: "Nee, niet zonder jouw toestemming. We bespreken eerst de functie of opdracht. Pas als jij akkoord bent, introduceren we je bij de opdrachtgever." }] : [service.faq[0], { question: "Welke informatie helpt bij een aanvraag?", answer: "Een korte omschrijving van het werk, het gewenste aantal uren, de locatie en de startdatum is genoeg om te beginnen. Het profiel werken we samen verder uit." }]} />
    <Section><p className="eyebrow">Meer over deze dienst</p><nav aria-label="Meer over werken met Wedeploy" className="flex flex-wrap gap-x-6 gap-y-3">{[["Werving & selectie", "#werving-selectie"], ["Detachering", "#detachering"], ["Interim & zzp", "#interim"], ["Detavast", "#detavast"]].filter(([, hash]) => hash !== `#${slug.replace("-amsterdam", "")}`).map(([label, hash]) => <a key={hash} href={`/expertise-diensten${hash}`} className="font-bold text-accent">{label}</a>)}<a href={isProfessional ? "/vacatures" : "/opdrachtgevers"} className="font-bold text-accent">{isProfessional ? "Vacatures & opdrachten" : "Voor opdrachtgevers"}</a></nav></Section>
    <ContactSection compact lockRole defaultRole={audience} context={page.label} heading={isProfessional ? "Laat je cv achter." : "Vertel wie je zoekt."} description={isProfessional ? "Vertel welke rol je zoekt en wanneer je beschikbaar bent. We bespreken of jouw profiel aansluit op een vraag." : "Een eerste omschrijving van de functie, taken en gewenste start is genoeg. We werken het profiel samen verder uit."} />
  </PageLayout>;
}
