import { ContactSection } from "@/components/ContactSection";
import { amsterdamServices, amsterdamPages } from "@/data/amsterdam";
import { PageLayout, Section, ActionLink, FAQ } from "@/components/PageLayout";
import NotFound from "./not-found";
export function AmsterdamServicePage({ slug, audience }: { slug: string; audience: "opdrachtgever" | "kandidaat" }) {
  const service = amsterdamServices.find(item => item.slug === slug);
  const page = amsterdamPages.find(item => item.slug === slug && item.audience === audience);
  if (!service || !page) return <NotFound />;
  const isProfessional = audience === "kandidaat";
  const contactHref = "#contact";
  const candidateSteps: Record<string, string[][]> = {
    "werving-selectie-amsterdam": [["Meer dan een functietitel", "Wat wil je doen in jouw volgende vaste baan? Vertel welke verantwoordelijkheden je zoekt, wat je wilt leren en welk team bij je past."], ["De voorwaarden bespreken", "We stemmen functie, uren en salariswensen met je af. Bij een passende vacature bespreken we een introductie bij de organisatie waar je rechtstreeks in dienst zou komen."]],
    "detachering-amsterdam": [["De opdracht begrijpen", "We bespreken wat de opdrachtgever nodig heeft, wie jouw aanspreekpunt wordt en hoe jouw ervaring aansluit op het team."], ["Weten waar je aan toe bent", "Vóór een mogelijke start bespreken we jouw arbeidsovereenkomst, arbeidsvoorwaarden en de afspraken over de inzet bij de opdrachtgever."]],
    "interim-amsterdam": [["Jouw projectervaring delen", "Welke resultaten heb je als zelfstandige bereikt? Deel relevante projecten, jouw beschikbaarheid, gewenste inzet en tariefindicatie."], ["De opdracht afstemmen", "We bespreken het beoogde resultaat, de looptijd, verantwoordelijkheden en werklocatie. Een mogelijke introductie stemmen we eerst met je af."]],
    "detavast-amsterdam": [["Beide fases bespreken", "We kijken naar de start via Wedeploy én naar de functie bij de opdrachtgever daarna. Jouw wensen voor de langere termijn horen vanaf het begin bij het gesprek."], ["Een bewuste vervolgstap", "Je hoort vooraf welke periode en voorwaarden worden voorgesteld. We bespreken hoe de samenwerking wordt geëvalueerd en wat de beoogde overstap inhoudt."]],
  };
  const steps = isProfessional ? candidateSteps[slug] : service.details;
  const candidateHeadings: Record<string, string> = { "werving-selectie-amsterdam": "Rechtstreeks in dienst.", "detachering-amsterdam": "Zo werkt detachering.", "interim-amsterdam": "Jouw inzet als zelfstandige.", "detavast-amsterdam": "De route naar vaste dienst." };
  const employerHeadings: Record<string, string> = { "werving-selectie-amsterdam": "Een vaste collega.", "detachering-amsterdam": "Tijdelijke versterking.", "interim-amsterdam": "Expertise voor jouw opdracht.", "detavast-amsterdam": "Een collega voor de toekomst." };
  const heroPhoto = !isProfessional && slug !== "detavast-amsterdam" ? (slug === "detachering-amsterdam" ? "/images/workplace.webp" : "/images/office-facade.webp") : undefined;
  return <PageLayout variant={isProfessional ? "editorial" : slug === "detavast-amsterdam" ? "navy" : "split"} image={heroPhoto} imageAlt={slug === "detachering-amsterdam" ? "Werkplekken in een modern kantoor" : "Detail van een glazen kantoorgevel"} hero={isProfessional && slug === "detachering-amsterdam" ? "graphic" : "type"} label={page.label} title={isProfessional ? service.professionalTitle : employerHeadings[slug]} intro={isProfessional ? service.professionalText : service.employerText} cta={isProfessional ? "Stuur jouw cv" : "Bespreek jouw vraag"} ctaHref={contactHref} secondary={{ label: isProfessional ? "Vacatures & opdrachten" : "Bekijk ons netwerk", href: isProfessional ? "/vacatures" : "/professionals" }}>
    <Section tone={isProfessional ? "white" : "plain"}><div className={isProfessional ? "candidate-story" : "grid md:grid-cols-[.85fr_1.15fr] gap-8 md:gap-16"}><div><p className="eyebrow">{isProfessional ? "Voor professionals" : "Voor opdrachtgevers"}</p><h2 className="section-title">{isProfessional ? candidateHeadings[slug] : "Van vraag naar zoekprofiel."}</h2><p className="mt-5 text-muted-foreground leading-relaxed">{isProfessional ? service.professionalNote : "Wat moet iemand oppakken? We bespreken de verantwoordelijkheden, de werkomgeving en de gewenste ervaring. Daarop bouwen we de zoektocht."}</p></div><div>{steps.map(([title, text]) => <article key={title} className="editorial-item"><h3 className="text-xl font-bold text-primary">{title}</h3><p className="mt-4 text-muted-foreground leading-relaxed">{text}</p></article>)}</div></div></Section>
    <Section tone="wash"><div className="sector-statement"><div><p className="eyebrow">Vastgoed, facility en projecten</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">{isProfessional ? "In jouw vakgebied." : "Wie past bij het werk?"}</h2></div><div><p className="text-muted-foreground leading-relaxed">{isProfessional ? "Onze focus ligt op vastgoedbeheer, huisvesting, Facility Management en projectondersteuning. Vertel met welke portefeuilles, dienstverlening of projecten je ervaring hebt en waarin je verder wilt." : "Een vastgoedbeheerder, facilitair coördinator, facility manager of projectondersteuner: we bespreken wat iemand moet oppakken en welke ervaring daarvoor nodig is. Daarna bepalen we samen de zoekaanpak."}</p><div className="mt-7"><ActionLink href={contactHref}>{isProfessional ? "Deel jouw ervaring" : "Bespreek jouw vacature"}</ActionLink></div></div></div></Section>
    <Section><div className="grid md:grid-cols-2 gap-8 md:gap-16"><div><p className="eyebrow">Vanuit Amsterdam</p><h2 className="section-title">{isProfessional ? "Jouw regio, jouw bereik." : "De praktische kant."}</h2></div><div className="space-y-4 text-muted-foreground leading-relaxed"><p>Wedeploy werkt vanuit IJburg in Amsterdam. We nemen de werklocatie en bereikbaarheid mee in het gesprek.</p><p>{isProfessional ? "Amsterdam is groter dan één werklocatie. Geef aan welke locaties voor jou bereikbaar zijn, hoeveel dagen je op locatie wilt werken en of je ook openstaat voor de omgeving. Dat nemen we mee in het gesprek." : "We bespreken de precieze werklocatie, benodigde aanwezigheid en mogelijkheden om hybride te werken. Zo krijgt een kandidaat vooraf een duidelijk beeld van de praktische kant van de functie of opdracht."}</p></div></div></Section>
    <FAQ items={isProfessional ? [{ question: "Kan ik mijn cv alvast insturen?", answer: "Ja. Vertel welke rol je zoekt, welke inzet bij je past en wanneer je beschikbaar bent. We bespreken jouw wensen en ervaring; een inschrijving is geen garantie op werk." }, { question: "Wordt mijn cv direct doorgestuurd?", answer: "Nee. We stemmen een mogelijke introductie eerst met je af. Een open inschrijving is een kennismaking en geen toezegging van een beschikbare functie of opdracht." }] : [service.faq[0], { question: "Wat gebeurt er na mijn aanvraag?", answer: "We nemen contact op om de inhoud, inzet en verwachtingen te bespreken. Daarna ontvang je een voorstel voor de aanpak en afspraken. We starten de zoektocht na akkoord." }]} />
    <Section><p className="eyebrow">Andere mogelijkheden in Amsterdam</p><nav aria-label="Diensten in Amsterdam" className="grid sm:grid-cols-2 gap-5">{amsterdamPages.filter(item => item.audience === audience && item.slug !== slug).map(item => <a key={item.path} href={item.path} className="text-primary font-bold">{amsterdamServices.find(service => service.slug === item.slug)?.serviceName}</a>)}</nav><p className="mt-8 text-sm text-muted-foreground">{isProfessional ? "Zoek je versterking voor jouw organisatie?" : "Zoek je zelf een functie of opdracht?"} <a href={amsterdamPages.find(item => item.slug === slug && item.audience !== audience)?.path ?? "/contact"} className="font-bold text-accent">{isProfessional ? "Voor opdrachtgevers" : "Voor professionals"}</a></p></Section>
    <ContactSection compact lockRole defaultRole={audience} context={page.label} heading={isProfessional ? "Stuur jouw cv." : "Vertel wie je zoekt."} />
  </PageLayout>;
}

export function AmsterdamLinks({ audience }: { audience: "opdrachtgever" | "kandidaat" }) {
  return <Section><p className="eyebrow">Amsterdam</p><h2 className="section-title mb-7">{audience === "kandidaat" ? "Hoe wil jij werken?" : "Vast of tijdelijk?"}</h2><nav aria-label={audience === "kandidaat" ? "Werken in Amsterdam" : "Personeel in Amsterdam"} className="grid sm:grid-cols-2 gap-5">{amsterdamPages.filter(page => page.audience === audience).map(page => <a href={page.path} key={page.path} className="font-bold text-primary">{amsterdamServices.find(service => service.slug === page.slug)?.serviceName}</a>)}</nav></Section>;
}
