import { serviceDetails } from "@/data/service-details";
import { vakgebieden, candidateSectorPages } from "@/data/vakgebieden";
import { AvailableProfessionals } from "@/components/AvailableProfessionals";
import { availableProfessionals } from "@/data/opportunities";
import { PageLayout, Section, ClosingCTA, ActionLink, FAQ } from "@/components/PageLayout";
import { ContactSection } from "@/components/ContactSection";
import { VacancyCards } from "@/components/VacancyCards";
import { services, vacancies } from "@/data/site";
import { DirectoryItem, EditorialSection, NumberedSection } from "@/components/PageSections";
const nickPhoto = "/nicky-verkooij.webp";

const employerFAQ = [
  { question: "Zoeken jullie ook voor andere vakgebieden?", answer: "Ja. Onze ervaring ligt vooral in projectmanagement, vastgoed, Facility Management, workplace en hospitality. Leg gerust een andere personeelsvraag voor; we bespreken eerlijk of we daarbij kunnen helpen." },
  { question: "Hoe worden de kosten bepaald?", answer: "Dat hangt af van de functie en inzetvorm. Je ontvangt vooraf een voorstel met de vergoeding en voorwaarden. We starten pas na akkoord." },
];
export function Employers() {
  return <PageLayout variant="split" hero="line" label="Opdrachtgevers" title="Wie versterkt jouw team?" intro="Een vaste collega of tijdelijke expertise. We zoeken gericht naar mensen die passen bij het werk en jouw team. Met heldere afspraken over de aanpak." cta="Bespreek jouw vacature" ctaHref="/contact?type=opdrachtgever" secondary={{ label: "Bekijk ons netwerk", href: "/professionals" }}>
    <EditorialSection eyebrow="Recruitment met praktijkervaring" title="We kennen het werk." offset><p>Een functietitel zegt veel, maar niet alles. Wat moet iemand oplossen? Hoe werkt het team? En welke ervaring maakt hier het verschil?</p><p>Onze ervaring ligt in het beheren van vastgoedportefeuilles, het aansturen van facilitaire teams en het begeleiden van huisvestings- en renovatieprojecten. Daardoor kunnen we doorvragen over verantwoordelijkheden, samenwerking en wat iemand in de praktijk moet kunnen.</p><p>Je spreekt rechtstreeks met degene die de zoektocht uitvoert. Dat maakt de samenwerking persoonlijk en de afspraken duidelijk.</p><a href="/over-ons" className="text-accent font-bold">Over Wedeploy</a></EditorialSection>
    <Section tone="white"><div className="mb-8"><p className="eyebrow">Onze diensten</p><h2 className="section-title">Vast of tijdelijk.</h2></div><div className="service-editorial-list">{services.map(service => <article className="editorial-item" key={service.id}><h3 className="text-xl font-bold text-primary mb-3">{service.title}</h3><p className="text-muted-foreground leading-relaxed">{service.description}</p><a href={service.id === "werving-selectie" ? "/werving-selectie" : service.id === "interim" ? "/interim-zzp" : service.id === "detavast" ? "/detachering#detavast" : "/detachering"} className="inline-flex items-center gap-2 text-accent text-sm font-bold mt-5">Meer over {service.title.toLowerCase()} </a></article>)}</div></Section>
    <Section navy><div className="grid md:grid-cols-2 gap-10 md:gap-16"><div><p className="eyebrow">Exclusieve werving & selectie</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">Eén aanspreekpunt.</h2><p className="mt-5 text-white/80 leading-relaxed">Bij een exclusieve zoekopdracht geef je Wedeploy de regie over de werving. We spreken af wie je zoekt, hoe we de markt benaderen en wanneer je een update krijgt.</p><p className="mt-4 text-white/80 leading-relaxed">Zo houden we de benadering van kandidaten en de terugkoppeling bij één aanspreekpunt. Jij kunt je richten op de kennismaking met passende professionals.</p><div className="mt-7"><ActionLink href="/contact?type=opdrachtgever&onderwerp=Exclusieve%20zoekopdracht">Bespreek jouw vacature</ActionLink></div></div><div className="divide-y divide-white/15">{[
      ["Een scherp zoekprofiel", "Je ontvangt een afgestemd zoekprofiel met de verantwoordelijkheden, gewenste ervaring en voorwaarden."],
      ["Actieve benadering", "We zoeken in ons netwerk én benaderen professionals die inhoudelijk bij de functie passen."],
      ["Een onderbouwde introductie", "We spreken iedere professional eerst in een persoonlijke intake. Bij een introductie ontvang je een toelichting op ervaring, motivatie en aansluiting op jouw vraag."],
      ["Afgesproken terugkoppeling", "We spreken af wanneer je een update krijgt. Je hoort hoe de zoektocht loopt en welke reacties aanleiding geven om het profiel of de aanpak bij te stellen."],
    ].map(([title, text]) => <article key={title} className="py-5 first:pt-0"><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/75">{text}</p></article>)}</div></div></Section>
    <NumberedSection eyebrow="Na jouw aanvraag" title="Van vraag naar aanpak." layout="steps" tone="plain" items={[
      { title: "Een eerste gesprek", body: <p>We bespreken jouw vacature, het team en de gewenste start. Dat gesprek is vrijblijvend.</p> },
      { title: "Het profiel scherpstellen", body: <p>Samen bepalen we welke ervaring, voorwaarden en verwachtingen bij de functie horen.</p> },
      { title: "Een helder voorstel", body: <p>Je ontvangt een voorstel voor de aanpak en vergoeding. Ook exclusiviteit en terugkoppeling leggen we vast.</p> },
      { title: "Gericht aan de slag", body: <p>Na akkoord zoeken en spreken we professionals. We begeleiden de introducties en vervolggesprekken.</p> },
    ]} />
    <FAQ items={employerFAQ} /><ClosingCTA title="Wie zoek je?" text="Vertel wat er moet gebeuren. Samen bepalen we het profiel en de zoekaanpak." label="Neem contact op" href="/contact?type=opdrachtgever" />
  </PageLayout>;
}
export function Professionals() {
  return <PageLayout variant="navy" label="Ons netwerk" title="Een professional voor jouw opdracht." intro="Ons brede netwerk bestaat uit professionals voor vaste functies en zelfstandigen voor tijdelijke opdrachten. Met expertise in projectmanagement, Facility Management en vastgoed. We kennen hun ervaring en wensen en zoeken gericht naar een aansluiting op jouw vraag." cta="Bespreek wie je zoekt" ctaHref="/contact?type=opdrachtgever&onderwerp=Ons%20netwerk#contact">
    {availableProfessionals.length > 0 && <Section><p className="eyebrow">Beschikbaar of binnenkort beschikbaar</p><h2 className="section-title mb-7">Professionals die we begeleiden.</h2><AvailableProfessionals /><p className="text-sm text-muted-foreground leading-relaxed mt-7 max-w-2xl">Openbare profielen zijn geanonimiseerd en worden met de professional afgestemd. Bij interesse bespreken we eerst jouw opdracht. Een naam, cv of introductie delen we na overleg met de professional.</p></Section>}
    <EditorialSection eyebrow="Een inhoudelijke introductie" title="Ervaring die aansluit op het werk." tone="white"><p>Beschikbaarheid alleen maakt iemand nog niet passend. In een persoonlijke intake bespreken we ervaring, motivatie en het werk dat iemand zoekt. Met jouw opdracht als vertrekpunt beoordelen we waar de aansluiting zit.</p><p>We stemmen uren, locatie, startdatum en voorwaarden af voordat we iemand voorstellen. Zo weet je wat actueel is en welke punten je samen verder moet bespreken.</p><p>We zoeken binnen ons netwerk en benaderen daarnaast professionals die aansluiten op jouw vraag. Een cv of introductie delen we pas na overleg en toestemming.</p></EditorialSection>
    <Section><p className="eyebrow">Onze vakgebieden</p><h2 className="section-title">Van projectregie tot dienstverlening.</h2><div className="role-directory mt-7">{Object.values(vakgebieden).map(area => <DirectoryItem key={area.path} href={area.path} title={area.label} description={area.description} label="Bekijk het vakgebied" />)}</div></Section>
    <ClosingCTA title="Wie zoek je?" text="Vertel over de opdracht, de gewenste ervaring en de start. We bespreken welke professional daarbij kan passen." label="Bespreek jouw opdracht" href="/contact?type=opdrachtgever&onderwerp=Professional%20zoeken#contact" />
  </PageLayout>;
}
export function Vacancies() {
  return <PageLayout variant="editorial" label="Vacatures & opdrachten" title="Jouw volgende stap." intro="Op zoek naar een vaste functie of tijdelijke opdracht? Bekijk actuele mogelijkheden en reageer rechtstreeks. Je kunt ook jouw cv achterlaten en vertellen welk werk je zoekt." cta={vacancies.length ? "Bekijk vacatures" : "Laat jouw cv achter"} ctaHref={vacancies.length ? "#actueel" : "#inschrijven"} secondary={{label:vacancies.length ? "Laat jouw cv achter" : "Ontdek jouw vakgebied",href:vacancies.length ? "#inschrijven" : "#vakgebieden"}}>
    <Section id="actueel" tone="white"><p className="eyebrow">Nu te bekijken</p><h2 className="section-title mb-7">Actuele vacatures & opdrachten.</h2><VacancyCards emptyVariant="listing" /></Section>
    <Section id="vakgebieden"><p className="eyebrow">Ontdek jouw vakgebied</p><h2 className="section-title">Welk werk wil jij doen?</h2><p className="text-muted-foreground max-w-2xl mt-5">Ontdek functies in projectmanagement, Facility Management en vastgoed. Bespreek met ons welk werk en welke organisatie bij jou passen.</p><div className="role-directory mt-7">{candidateSectorPages.map(page => <DirectoryItem key={page.path} href={page.path} title={page.label} description={page.description} label="Ontdek de mogelijkheden" />)}<DirectoryItem href="/zzp-opdrachten" title="Zelfstandig en beschikbaar?" description="Bespreek jouw expertise, gewenste opdrachten en beschikbaarheid. Ook als je huidige opdracht nog loopt." label="Deel jouw beschikbaarheid" /></div></Section>
    <EditorialSection eyebrow="Na jouw reactie" title="Je weet waar je aan toe bent." tone="white"><p>Na jouw reactie nemen we contact met je op om een persoonlijke intake te plannen. We bespreken jouw ervaring, motivatie en wensen. Zo leren we de persoon achter het cv kennen.</p><p>Ook zonder openstaande vacature maken we graag kennis. In de intake bespreken we welk werk je zoekt en wat bij jou past. Is er een passende mogelijkheid, dan bespreken we de functie en organisatie eerst met jou. We delen je cv alleen met jouw toestemming.</p><p>Zoek je een andere functie dan de vakgebieden op de site? Laat weten wat je zoekt. We bespreken eerlijk of we iets voor je kunnen betekenen.</p></EditorialSection>
    <div id="inschrijven"><ContactSection compact lockRole readQuery defaultRole="kandidaat" heading="Laat jouw cv achter." description="Laat jouw cv achter. We nemen contact met je op om een persoonlijke intake te plannen. We zijn benieuwd naar jouw ervaring, wensen en de persoon achter het cv." context="Open inschrijving" /></div>
  </PageLayout>;
}
export function ExpertiseServices() {
  return <PageLayout label="Expertise & diensten" title="Het werk begrijpen. De juiste mensen zoeken." intro="Projectmanagement en PMO, Facility Management en vastgoed vormen de kern van onze ervaring. We bemiddelen voor vaste functies en tijdelijke opdrachten. Ook een andere personeelsvraag bespreken we graag." cta="Bespreek jouw personeelsvraag" ctaHref="/contact?type=opdrachtgever#contact" secondary={{label:"Ik zoek werk",href:"/vacatures"}}>
    <Section><p className="eyebrow">Onze vakgebieden</p><h2 className="section-title">Van regie tot uitvoering.</h2><div className="role-directory mt-7">{Object.values(vakgebieden).map(area => <DirectoryItem key={area.path} href={area.path} title={area.label} description={area.description} label="Meer over dit vakgebied" />)}</div></Section>
    <Section tone="white"><p className="eyebrow">Onze diensten</p><h2 className="section-title">Vast of tijdelijk. Met heldere afspraken.</h2><div className="service-detail-list mt-7">{services.map(service => <article id={service.id} className="service-detail" key={service.id}><header className="service-detail-heading"><h3 className="text-2xl font-bold text-primary">{service.title}</h3></header><div><p className="text-muted-foreground leading-relaxed">{service.description}</p><p className="text-sm text-muted-foreground leading-relaxed mt-3">{service.audience}</p><a className="inline-flex text-sm font-bold text-accent mt-5" href={serviceDetails[service.id].employerPath}>Zo werkt {service.title.toLowerCase()}</a></div></article>)}</div></Section>
    <div id="andere-functies"><EditorialSection eyebrow="Ook binnen jouw team" title="Management en ondersteuning."><p>Een vakgebied bestaat uit meer dan specialisten. Ook teamleiders, afdelingsmanagers, office managers, managementassistenten en administratief medewerkers kunnen een organisatie versterken. We bespreken het takenpakket en de omgeving waarin iemand moet werken.</p><p>Projectondersteuning en PMO behandelen we bij projectmanagement. Workplace en hospitality vallen onder Facility Management. Zo blijft de samenhang met het werk duidelijk, zonder voor iedere functietitel een aparte pagina te maken.</p><a href="/contact?type=opdrachtgever&onderwerp=Andere%20personeelsvraag#contact" className="text-accent font-bold">Leg jouw personeelsvraag voor</a></EditorialSection></div>
    <FAQ items={[{question:"Wat is het verschil tussen werving, detachering en interim?",answer:"Bij werving & selectie komt de professional rechtstreeks bij jouw organisatie in dienst. Bij detachering is Wedeploy de werkgever. Interim beschrijft tijdelijke inzet; de contractvorm bespreken we aan de hand van de opdracht."},{question:"Zoeken jullie ook buiten deze vakgebieden?",answer:"Ja, je kunt een andere vraag voorleggen. We bespreken de functie en geven eerlijk aan of we de zoektocht kunnen uitvoeren. Onze praktijkervaring ligt vooral in projectmanagement, Facility Management en vastgoed."}]} />
    <ClosingCTA title="Wat heeft jouw team nodig?" text="Een eerste omschrijving van het werk is genoeg. We bespreken samen het profiel en de passende samenwerking." label="Bespreek jouw personeelsvraag" href="/contact?type=opdrachtgever#contact" />
  </PageLayout>;
}
export function About() {
  return <PageLayout variant="quiet" label="Over Wedeploy" title="Praktijkkennis. Persoonlijk contact." intro="Wedeploy verbindt organisaties en professionals. Voor vaste functies via werving & selectie en voor tijdelijke inzet via detachering, interim en zzp." cta="Bespreek jouw vraag" ctaHref="/contact">
    <Section><div className="grid md:grid-cols-[0.8fr_1.2fr] gap-10 md:gap-16 items-center"><div className="portrait-frame overflow-hidden"><img src={nickPhoto} alt="Nicky, consultant van Wedeploy" width="600" height="700" className="w-full max-h-[480px] object-cover object-top" loading="lazy" /></div><div><p className="eyebrow">Nicky · Consultant</p><h2 className="section-title">Van vakkennis naar recruitment.</h2><div className="mt-6 space-y-4 text-muted-foreground leading-relaxed"><p>Wedeploy is ontstaan vanuit ervaring met het beheren van vastgoedportefeuilles, het aansturen van facilitaire teams en het begeleiden van huisvestings- en renovatieprojecten. We kennen de samenwerking tussen gebruikers, leveranciers en projectteams. Die praktijkkennis helpt ons te begrijpen wie een organisatie nodig heeft.</p><p>Kwaliteit boven kwantiteit. We nemen de tijd om een vraag te begrijpen en zoeken gericht binnen én buiten ons netwerk.</p><p>We willen de persoon achter het cv leren kennen. Daarom plannen we altijd een persoonlijke intake voordat we iemand voorstellen. We bespreken ervaring, motivatie en ambities, maar ook wat iemand zoekt in een team en werkomgeving.</p><p>Voor opdrachtgevers begint de zoektocht met een gesprek over het werk, het team en de gewenste ervaring. Samen maken we het zoekprofiel scherp. We zoeken en benaderen professionals en lichten toe waarom we iemand voorstellen. Je hebt rechtstreeks contact met ons en krijgt duidelijke terugkoppeling over de zoektocht.</p></div><div className="mt-7"><ActionLink href="/contact">Laten we kennismaken</ActionLink></div></div></div></Section>
    <NumberedSection eyebrow="Onze manier van werken" title="Inhoud. Contact. Afspraken." layout="steps" items={[
      { title: "Inhoudelijk betrokken", body: <p>We verdiepen ons in de personeelsvraag, de werkzaamheden en het team. Zo zoeken we op meer dan een functietitel.</p> },
      { title: "Persoonlijk contact", body: <p>Een persoonlijke intake om te begrijpen wie je bent, wat je kunt en welk werk bij jou past.</p> },
      { title: "Duidelijke afspraken", body: <p>Vooraf weten waar je aan toe bent. Over inzet, verwachtingen en voorwaarden.</p> },
    ]} />
    <ClosingCTA />
  </PageLayout>;
}
export function Contact() {
  return <PageLayout variant="quiet" hero="contact" label="Contact" title="Laten we praten." intro="Een professional nodig of toe aan een volgende stap? Neem vrijblijvend contact op met ons.">
    <EditorialSection eyebrow="Samenwerken" title="Ook voor bureaus."><p>Ben je een bureau of dienstverlener en zoek je aanvullende expertise? We bespreken graag hoe we elkaar kunnen versterken met ons netwerk en een gerichte zoektocht.</p><a href="/contact?type=opdrachtgever&onderwerp=Samenwerking%20tussen%20bureaus#contact" className="text-accent font-bold">Bespreek een samenwerking</a></EditorialSection>
    <Section><div className="flex flex-wrap gap-5"><a href="tel:+31852128668" className="inline-flex items-center font-bold text-lg text-primary">085 212 8668</a><a href="mailto:info@wedeploy.nl" className="inline-flex items-center font-bold text-lg text-primary">info@wedeploy.nl</a></div></Section><ContactSection compact heading="Stuur jouw bericht." description="Vertel kort waarover je contact wilt opnemen. We lezen je bericht en nemen contact met je op om de vraag of mogelijkheden te bespreken." readQuery />
  </PageLayout>;
}
export function Privacy() {
  return <PageLayout variant="quiet" label="Privacy" title="Jouw gegevens, zorgvuldig behandeld." intro="Wanneer je contact opneemt of een cv instuurt, gebruik je persoonsgegevens. Hieronder lees je waarvoor Wedeploy die gegevens gebruikt.">
    <Section><div className="max-w-3xl space-y-8 text-muted-foreground leading-relaxed">{[
      ["Welke gegevens ontvangen we?", "Via het formulier ontvangen we jouw naam, e-mailadres, eventueel telefoonnummer, bericht en het cv dat je zelf uploadt. Bij een aanvraag kan ook een functietitel of profielreferentie worden meegestuurd."],
      ["Waarvoor gebruiken we die gegevens?", "We gebruiken ze om jouw vraag te beantwoorden, contact te onderhouden en een mogelijke samenwerking of sollicitatie te bespreken. We delen een herkenbaar kandidaatprofiel of cv met een mogelijke opdrachtgever pas na afstemming met jou."],
      ["Hoe worden gegevens verwerkt?", "De website wordt gehost via Vercel. Formulierberichten en eventuele cv-bijlagen worden via Resend naar de mailbox van Wedeploy gestuurd. We beperken toegang tot de gegevens tot wie die nodig heeft voor de behandeling van jouw vraag."],
      ["Hoe lang bewaren we gegevens?", "We bewaren gegevens niet langer dan nodig voor het contact, de sollicitatie of de afgesproken samenwerking. Willen we jouw cv ook voor toekomstige mogelijkheden bewaren, dan bespreken we dat met je."],
      ["Jouw gegevens inzien of verwijderen", "Wil je weten welke gegevens we van je hebben, iets aanpassen of jouw cv laten verwijderen? Mail naar info@wedeploy.nl. Je kunt daar ook vragen stellen over deze verklaring."],
      ["Cookies", "Deze website gebruikt in de huidige versie geen advertentie- of analysetrackers. Als we die toevoegen, passen we deze informatie en eventuele toestemmingsinstellingen aan."],
    ].map(([title,text]) => <section key={title}><h2 className="text-xl font-bold text-primary mb-3">{title}</h2><p>{text}</p></section>)}</div></Section>
  </PageLayout>;
}
