import { serviceDetails } from "@/data/service-details";
import { vakgebieden, candidateSectorPages } from "@/data/vakgebieden";
import { AvailableProfessionals } from "@/components/AvailableProfessionals";
import { availableProfessionals } from "@/data/opportunities";
import { PageLayout, Section, ClosingCTA, ActionLink, FAQ } from "@/components/PageLayout";
import { ContactSection } from "@/components/ContactSection";
import { VacancyCards } from "@/components/VacancyCards";
import { services, vacancies } from "@/data/site";
import { aboutFAQ, candidateFAQ, contactFAQ, networkFAQ } from "@/data/page-faqs";
import { DirectoryItem, EditorialSection, NumberedSection } from "@/components/PageSections";
const nickPhoto = "/nicky-verkooij.webp";

const employerFAQ = [
  { question: "Zoeken jullie ook voor andere vakgebieden?", answer: "Ja. Onze ervaring ligt vooral in projectmanagement, vastgoed, Facility Management, workplace en hospitality. Leg gerust een andere personeelsvraag voor; we bespreken eerlijk of we daarbij kunnen helpen." },
  { question: "Hoe worden de kosten bepaald?", answer: "Dat hangt af van de functie en inzetvorm. Je ontvangt vooraf een voorstel met de vergoeding en voorwaarden. We starten pas na akkoord." },
];
export function Employers() {
  return <PageLayout variant="split" hero="line" label="Opdrachtgevers" title="Wie versterkt jouw team?" intro="Een vaste collega of tijdelijke expertise. We zoeken gericht naar mensen die passen bij het werk en jouw team. Met heldere afspraken over de aanpak." cta="Bespreek jouw vacature" ctaHref="/contact?type=opdrachtgever" secondary={{ label: "Bekijk ons netwerk", href: "/professionals" }}>
    <EditorialSection eyebrow="Recruitment vanuit de praktijk" title="De juiste mensen voor jouw organisatie" offset><p>Een nieuwe collega, tijdelijke versterking of ervaring voor een project. We helpen organisaties met werving & selectie, detachering en interim.</p><p>Onze achtergrond in projectmanagement, Facility Management en vastgoed helpt ons om de vraag te begrijpen. We zoeken gericht en leren iedere professional persoonlijk kennen.</p><a href="/over-ons" className="action-arrow text-accent font-bold">Over Wedeploy</a></EditorialSection>
    <Section tone="white"><div className="mb-8"><p className="eyebrow">Onze diensten</p><h2 className="section-title">Vast of tijdelijk.</h2></div><div className="service-editorial-list">{services.map(service => <article className="editorial-item" key={service.id}><h3 className="text-xl font-bold text-primary mb-3">{service.title}</h3><p className="text-muted-foreground leading-relaxed">{service.description}</p><a href={service.id === "werving-selectie" ? "/werving-selectie" : service.id === "interim" ? "/interim-zzp" : service.id === "detavast" ? "/detachering#detavast" : "/detachering"} className="action-arrow inline-flex items-center gap-2 text-accent text-sm font-bold mt-5">Meer over {service.title.toLowerCase()} </a></article>)}</div></Section>
    <Section navy><div className="grid md:grid-cols-2 gap-10 md:gap-16"><div><p className="eyebrow">Exclusieve werving & selectie</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">Eén aanspreekpunt.</h2><p className="mt-5 text-white/80 leading-relaxed">Bij een exclusieve zoekopdracht geef je Wedeploy de regie over de werving. We spreken af wie je zoekt, hoe we de markt benaderen en wanneer je een update krijgt.</p><p className="mt-4 text-white/80 leading-relaxed">Zo houden we de benadering van kandidaten en de terugkoppeling bij één aanspreekpunt. Jij kunt je richten op de kennismaking met passende professionals.</p><div className="mt-7"><ActionLink href="/contact?type=opdrachtgever&onderwerp=Exclusieve%20zoekopdracht">Bespreek jouw vacature</ActionLink></div></div><div className="divide-y divide-white/15">{[
      ["Een scherp zoekprofiel", "Je ontvangt een afgestemd zoekprofiel met de verantwoordelijkheden, gewenste ervaring en voorwaarden."],
      ["Actieve benadering", "We zoeken in ons netwerk én benaderen professionals die inhoudelijk bij de functie passen."],
      ["Persoonlijke kennismaking", "We leren iedere professional persoonlijk kennen. Ervaring, motivatie en ambities wegen mee in de keuze."],
      ["Een gerichte zoektocht", "We richten ons op mensen die passen bij de functie en de organisatie."],
    ].map(([title, text]) => <article key={title} className="py-5 first:pt-0"><h3 className="text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/75">{text}</p></article>)}</div></div></Section>
    <NumberedSection eyebrow="Na jouw aanvraag" title="Van vraag naar aanpak." layout="steps" tone="plain" items={[
      { title: "Een eerste gesprek", body: <p>We bespreken jouw vacature, het team en de gewenste start. Dat gesprek is vrijblijvend.</p> },
      { title: "Het profiel scherpstellen", body: <p>Samen bepalen we welke ervaring, voorwaarden en verwachtingen bij de functie horen.</p> },
      { title: "Een helder voorstel", body: <p>Je ontvangt een voorstel voor de aanpak en vergoeding. Ook exclusiviteit en terugkoppeling leggen we vast.</p> },
      { title: "Gericht aan de slag", body: <p>Na akkoord zoeken en spreken we professionals. We begeleiden de introducties en vervolggesprekken.</p> },
    ]} />
    <FAQ items={employerFAQ} /><ClosingCTA title="Wie zoek je?" text="Vertel wat er moet gebeuren. Samen bepalen we het profiel en de zoekaanpak." label="Neem contact op" href="/contact?type=opdrachtgever" />
  </PageLayout>;
}
export function Professionals() {
  const hasProfiles = availableProfessionals.length > 0;
  return <PageLayout variant="navy" label="Ons netwerk" title="Ons netwerk van professionals" intro="Een vaste collega of tijdelijke versterking? Maak kennis met professionals die we begeleiden. Ons netwerk omvat projectmanagement, procesverbetering, Facility Management, vastgoed en techniek." cta={hasProfiles ? "Bekijk de professionals" : "Bespreek wie je zoekt"} ctaHref={hasProfiles ? "#beschikbare-professionals" : "/contact?type=opdrachtgever&onderwerp=Ons%20netwerk#contact"} secondary={{label:"Bespreek wie je zoekt",href:"/contact?type=opdrachtgever&onderwerp=Ons%20netwerk#contact"}}>
    {hasProfiles && <Section id="beschikbare-professionals" tone="white"><p className="eyebrow">Nu of binnenkort beschikbaar</p><h2 className="section-title">Een greep uit ons netwerk</h2><p className="section-lead mb-7">Maak kennis met een aantal professionals die wij begeleiden naar een vaste functie of nieuwe opdracht.</p><AvailableProfessionals /><p className="text-sm text-muted-foreground leading-relaxed mt-7 whitespace-nowrap">Interesse? Vraag het profiel op.</p></Section>}
    <Section><p className="eyebrow">Onze vakgebieden</p><h2 className="section-title">Meer in ons netwerk</h2><p className="section-lead">Ons netwerk omvat professionals in projectmanagement, Facility Management, vastgoed en techniek. Volg Wedeploy op LinkedIn voor nieuwe profielen en ontwikkelingen, of bespreek rechtstreeks met ons wie je zoekt.</p><div className="text-link-list mt-5"><a href="https://www.linkedin.com/company/wedeploy/" target="_blank" rel="noopener noreferrer" className="action-arrow">Volg ons op LinkedIn<span className="sr-only"> (opent in een nieuw tabblad)</span></a><a href="/contact?type=opdrachtgever&onderwerp=Ons%20netwerk#contact" className="action-arrow">Bespreek jouw personeelsvraag</a></div><div className="role-directory mt-7">{Object.values(vakgebieden).map(area => <DirectoryItem key={area.path} href={area.path} title={area.label} description={area.description} label="Bekijk het vakgebied" />)}</div><aside className="network-question"><div><h3>Op zoek naar iemand anders?</h3><p>Staat de functie die je zoekt er niet tussen? Vertel ons wie je nodig hebt. We bespreken graag hoe we kunnen helpen.</p></div><ActionLink href="/contact?type=opdrachtgever&onderwerp=Andere%20functie#contact">Bespreek wie je zoekt</ActionLink></aside></Section>
    <EditorialSection eyebrow="Persoonlijk kennismaken" title="Meer dan een cv" tone="wash"><p>Iedere professional spreken we in een persoonlijke intake. We kijken naar ervaring, motivatie en ambities én naar wat past bij de organisatie en het team.</p><p>Een naam of cv delen we alleen na overleg en toestemming. De kennismaking loopt via Wedeploy.</p><a href="/opdrachtgevers" className="action-arrow text-accent font-semibold">Onze aanpak voor opdrachtgevers</a></EditorialSection>
    <FAQ items={networkFAQ} /><ClosingCTA title="Wie zoek je?" text="Interesse in een profiel of een andere personeelsvraag? Vertel ons welke versterking jouw organisatie nodig heeft." label="Bespreek jouw personeelsvraag" href="/contact?type=opdrachtgever&onderwerp=Professional%20zoeken#contact" />
  </PageLayout>;
}
export function Vacancies() {
  return <PageLayout variant="editorial" label="Vacatures & opdrachten" title="Vacatures & opdrachten" intro="Op zoek naar een vaste functie of tijdelijke opdracht? Bekijk actuele mogelijkheden en reageer rechtstreeks. Je kunt ook jouw cv achterlaten en vertellen welk werk je zoekt." cta={vacancies.length ? "Bekijk vacatures" : "Laat jouw cv achter"} ctaHref={vacancies.length ? "#actueel" : "#inschrijven"} secondary={{label:vacancies.length ? "Laat jouw cv achter" : "Ontdek jouw vakgebied",href:vacancies.length ? "#inschrijven" : "#vakgebieden"}}>
    <Section id="actueel" tone="white"><p className="eyebrow">Nu te bekijken</p><h2 className="section-title mb-3">Vind werk dat bij jou past</h2><p className="section-lead mb-7">Bekijk de actuele vacatures en opdrachten. Staat jouw volgende stap er niet tussen? Laat je cv achter; we maken graag kennis.</p><VacancyCards emptyVariant="listing" /></Section>
    <Section id="vakgebieden"><p className="eyebrow">Ontdek jouw vakgebied</p><h2 className="section-title">Welk werk wil jij doen?</h2><p className="text-muted-foreground max-w-2xl mt-5">Ontdek functies in projectmanagement, Facility Management en vastgoed. Bespreek met ons welk werk en welke organisatie bij jou passen.</p><div className="role-directory mt-7">{candidateSectorPages.map(page => <DirectoryItem key={page.path} href={page.path} title={page.label} description={page.description} label="Ontdek de mogelijkheden" />)}<DirectoryItem href="/zzp-opdrachten" title="Zelfstandig en beschikbaar?" description="Bespreek jouw expertise, gewenste opdrachten en beschikbaarheid. Ook als je huidige opdracht nog loopt." label="Deel jouw beschikbaarheid" /></div></Section>
    <EditorialSection eyebrow="Na jouw reactie" title="Je weet waar je aan toe bent." tone="white"><p>Na jouw reactie nemen we contact met je op om een persoonlijke intake te plannen. We bespreken jouw ervaring, motivatie en wensen. Zo leren we de persoon achter het cv kennen.</p><p>Ook zonder openstaande vacature maken we graag kennis. In de intake bespreken we welk werk je zoekt en wat bij jou past. Is er een passende mogelijkheid, dan bespreken we de functie en organisatie eerst met jou. We delen je cv alleen met jouw toestemming.</p><p>Zoek je een andere functie dan de vakgebieden op de site? Laat weten wat je zoekt. We bespreken eerlijk of we iets voor je kunnen betekenen.</p></EditorialSection>
    <FAQ items={candidateFAQ} /><div id="inschrijven"><ContactSection compact lockRole readQuery defaultRole="kandidaat" heading="Laat jouw cv achter." description="Laat jouw cv achter. We nemen contact met je op om een persoonlijke intake te plannen. We zijn benieuwd naar jouw ervaring, wensen en de persoon achter het cv." context="Open inschrijving" /></div>
  </PageLayout>;
}
export function ExpertiseServices() {
  return <PageLayout label="Expertise & diensten" title="Expertise & diensten" intro="Projectmanagement en PMO, Facility Management en vastgoed vormen de kern van onze ervaring. We bemiddelen voor vaste functies en tijdelijke opdrachten. Ook een andere personeelsvraag bespreken we graag." cta="Bespreek jouw personeelsvraag" ctaHref="/contact?type=opdrachtgever#contact" secondary={{label:"Ik zoek werk",href:"/vacatures"}}>
    <Section><p className="eyebrow">Onze vakgebieden</p><h2 className="section-title">Praktijkkennis voor jouw personeelsvraag</h2><p className="section-lead">Onze ervaring ligt in projectmanagement, Facility Management en vastgoed. Binnen deze vakgebieden zoeken we voor vaste functies en tijdelijke opdrachten, van management tot ondersteuning.</p><div className="role-directory mt-7">{Object.values(vakgebieden).map(area => <DirectoryItem key={area.path} href={area.path} title={area.label} description={area.description} label="Meer over dit vakgebied" />)}</div></Section>
    <Section tone="white"><p className="eyebrow">Onze diensten</p><h2 className="section-title">Vast of tijdelijk. Met heldere afspraken.</h2><div className="service-detail-list mt-7">{services.map(service => <article id={service.id} className="service-detail" key={service.id}><header className="service-detail-heading"><h3 className="text-2xl font-bold text-primary">{service.title}</h3></header><div><p className="text-muted-foreground leading-relaxed">{service.description}</p><p className="text-sm text-muted-foreground leading-relaxed mt-3">{service.audience}</p><a className="action-arrow inline-flex text-sm font-bold text-accent mt-5" href={serviceDetails[service.id].employerPath}>Zo werkt {service.title.toLowerCase()}</a></div></article>)}</div></Section>
    <div id="andere-functies"><EditorialSection eyebrow="Ook binnen jouw team" title="Management en ondersteuning."><p>Een vakgebied bestaat uit meer dan specialisten. Ook teamleiders, afdelingsmanagers, office managers, managementassistenten en administratief medewerkers kunnen een organisatie versterken. We bespreken het takenpakket en de omgeving waarin iemand moet werken.</p><p>De inhoud van het werk staat voorop. Een managementassistent in een projectteam heeft bijvoorbeeld andere ervaring nodig dan een office manager die een locatie organiseert. Ook bij managementfuncties bespreken we de teamomvang, verantwoordelijkheden en de omgeving waarin iemand moet werken.</p><a href="/contact?type=opdrachtgever&onderwerp=Andere%20personeelsvraag#contact" className="action-arrow text-accent font-bold">Leg jouw personeelsvraag voor</a></EditorialSection></div>
    <FAQ items={[{question:"Wat is het verschil tussen werving, detachering en interim?",answer:"Bij werving & selectie komt de professional rechtstreeks bij jouw organisatie in dienst. Bij detachering is Wedeploy de werkgever. Interim beschrijft tijdelijke inzet; de contractvorm bespreken we aan de hand van de opdracht."},{question:"Zoeken jullie ook buiten deze vakgebieden?",answer:"Ja, je kunt een andere vraag voorleggen. We bespreken de functie en geven eerlijk aan of we de zoektocht kunnen uitvoeren. Onze praktijkervaring ligt vooral in projectmanagement, Facility Management en vastgoed."}]} />
    <ClosingCTA title="Wat heeft jouw team nodig?" text="Een eerste omschrijving van het werk is genoeg. We bespreken samen het profiel en de passende samenwerking." label="Bespreek jouw personeelsvraag" href="/contact?type=opdrachtgever#contact" />
  </PageLayout>;
}
export function About() {
  return <PageLayout variant="quiet" label="Over Wedeploy" title="Over Wedeploy" intro="Wedeploy verbindt organisaties en professionals. Voor vaste functies via werving & selectie en voor tijdelijke inzet via detachering, interim en zzp." cta="Bespreek jouw vraag" ctaHref="/contact">
<Section><div className="about-story"><h2 className="section-title">Recruitment vanuit de praktijk</h2><div className="mt-6 space-y-4 text-muted-foreground leading-relaxed"><p>Wedeploy is ontstaan vanuit ervaring in projectmanagement, Facility Management en vastgoed. We kennen de praktijk van organisaties, teams en projecten en verbinden die ervaring met een breed netwerk van professionals.</p><p>We kijken verder dan het cv. We zoeken naar mensen die passen bij een organisatie én naar functies en opdrachten die passen bij de persoon.</p><p>Daarom begint het altijd met een persoonlijke kennismaking. We willen weten wat een organisatie nodig heeft en wie de professional achter het cv is.</p></div></div></Section>
    <EditorialSection eyebrow="Samenwerken met Wedeploy" title="Een match van beide kanten" tone="white"><p>Voor organisaties gaat het om de juiste ervaring en een goede aanvulling op het team. Voor professionals om een plek waar hun kennis, motivatie en ambities tot hun recht komen.</p><p>Die twee brengen we samen. Voor een vaste baan, tijdelijke versterking of een nieuwe opdracht.</p></EditorialSection><FAQ items={aboutFAQ} /><ClosingCTA text="Een professional nodig of zelf toe aan een volgende stap? Vertel ons wat je zoekt. We bespreken graag de mogelijkheden." portrait={{src:nickPhoto,alt:"Nicky, consultant van Wedeploy",name:"Nicky",role:"Consultant"}} />
  </PageLayout>;
}
export function Contact() {
  return <PageLayout variant="quiet" hero="contact" label="Contact" title="Contact met Wedeploy" intro="Een professional nodig of toe aan een volgende stap? Neem vrijblijvend contact op met ons." cta="Stuur jouw bericht" ctaHref="#contact" secondary={{label:"Bel 085 212 8668",href:"tel:+31852128668"}}>
    <Section className="contact-direct"><div><a href="tel:+31852128668">085 212 8668</a><a href="mailto:info@wedeploy.nl">info@wedeploy.nl</a></div></Section>
    <ContactSection compact heading="Stuur jouw bericht" description="Vertel welke professional je zoekt, welk werk je wilt doen of waarover je wilt samenwerken. We nemen contact op om jouw vraag te bespreken." readQuery />
    <EditorialSection eyebrow="Samenwerken" title="Ook voor bureaus en dienstverleners" tone="wash"><p>Zoek je aanvullende expertise voor jouw opdrachtgever of project? We bespreken graag hoe ons netwerk en een gerichte zoektocht jouw dienstverlening kunnen versterken.</p><p>We stemmen vooraf af wie de contacten begeleidt, welke inzet je zoekt en hoe we samenwerken. Zo is duidelijk wat jouw bureau, de professional en Wedeploy van elkaar kunnen verwachten.</p><a href="/contact?type=opdrachtgever&onderwerp=Samenwerking%20tussen%20bureaus#contact" className="action-arrow text-accent font-semibold">Bespreek een samenwerking</a></EditorialSection>
    <FAQ items={contactFAQ} />
  </PageLayout>;
}
export function Privacy() {
  return <PageLayout variant="quiet" label="Privacy" title="Jouw gegevens, zorgvuldig behandeld." intro="Wanneer je contact opneemt of een cv instuurt, gebruik je persoonsgegevens. Hieronder lees je waarvoor Wedeploy die gegevens gebruikt.">
    <Section><div className="max-w-3xl space-y-8 text-muted-foreground leading-relaxed">{[
      ["Welke gegevens ontvangen we?", "Via het formulier ontvangen we jouw naam, e-mailadres, eventueel telefoonnummer, bericht en het cv dat je zelf uploadt. Bij een aanvraag kan ook een functietitel of profielreferentie worden meegestuurd."],
      ["Waarvoor gebruiken we die gegevens?", "We gebruiken ze om jouw vraag te beantwoorden, contact te onderhouden en een mogelijke samenwerking of sollicitatie te bespreken. We delen een herkenbaar kandidaatprofiel of cv met een mogelijke opdrachtgever pas na afstemming met jou."],
      ["Hoe worden gegevens verwerkt?", "De website wordt gehost via Vercel. Formulierberichten en eventuele cv-bijlagen worden via Resend naar de mailbox van Wedeploy gestuurd. We beperken toegang tot de gegevens tot wie die nodig heeft voor de behandeling van jouw vraag."],
      ["Hoe lang bewaren we gegevens?", "We bewaren gegevens niet langer dan nodig voor het contact, de sollicitatie of de afgesproken samenwerking. Willen we jouw cv ook voor toekomstige mogelijkheden bewaren, dan bespreken we dat met je."],
      ["Jouw gegevens inzien of verwijderen", "Wil je weten welke gegevens we van je hebben, iets aanpassen of jouw cv laten verwijderen? Mail naar info@wedeploy.nl. Je kunt daar ook vragen stellen over deze verklaring."],
      ["Cookies", "Deze website gebruikt in de huidige versie geen advertentie- of analysetrackers. Als we die toevoegen, passen we deze informatie en eventuele toestemmingsinstellingen aan."],
    ].map(([title,text]) => <section key={title}><h2 className="text-xl font-bold text-primary mb-3">{title}</h2><p>{text}</p></section>)}</div></Section>
  </PageLayout>;
}
