import { ArrowRight, Check, Phone, Mail } from "lucide-react";
import { PageLayout, Section, ClosingCTA, ActionLink, FAQ } from "@/components/PageLayout";
import { ContactSection } from "@/components/ContactSection";
import { ProfessionalCards } from "@/components/ProfessionalCards";
import { VacancyCards } from "@/components/VacancyCards";
import { expertise, services } from "@/data/site";
const nickPhoto = "/nicky-verkooij.webp";

const employerFAQ = [
  { question: "Kunnen jullie exclusief voor ons zoeken?", answer: "Ja. Bij een exclusieve zoekopdracht spreken we het profiel, de aanpak en de planning samen af. Je hebt één aanspreekpunt en krijgt gerichte terugkoppeling over de zoektocht." },
  { question: "Wat kost werving & selectie?", answer: "Dat hangt af van de functie en de afgesproken aanpak. Na een eerste gesprek ontvang je een voorstel. We leggen de vergoeding en voorwaarden vast voordat de zoektocht begint." },
  { question: "Werken jullie alleen in Amsterdam?", answer: "WeDeploy is gevestigd in Amsterdam en bemiddelt ook daarbuiten. We kijken per opdracht naar de locatie, reisafstand en mogelijkheden om hybride te werken." },
];
export function Employers() {
  return <PageLayout label="Opdrachtgevers" title="Wie heb je nodig om verder te komen?" intro="Een nieuwe collega, tijdelijke versterking of iemand die een project verder brengt. WeDeploy zoekt gericht naar professionals in vastgoed, Facility Management, projectmanagement en techniek." cta="Bespreek jouw personeelsvraag" ctaHref="/contact?type=opdrachtgever" secondary={{ label: "Bekijk ons netwerk", href: "/professionals" }}>
    <Section><div className="grid md:grid-cols-2 gap-10 md:gap-20 items-start"><div><p className="eyebrow">Recruitment met praktijkervaring</p><h2 className="section-title">We begrijpen het werk achter de vacature.</h2></div><div className="space-y-5 text-muted-foreground leading-relaxed"><p>Een functietitel zegt veel, maar niet alles. Wat moet iemand oplossen? Hoe werkt het team? En welke ervaring maakt hier het verschil?</p><p>Oprichter Nicky Verkooij heeft zelf facilitaire en vastgoedteams geleid en projecten begeleid. Die ervaring gebruiken we om jouw vraag scherp te krijgen en kandidaten inhoudelijk te beoordelen.</p><p>Je spreekt rechtstreeks met degene die de zoektocht uitvoert. Dat maakt de samenwerking persoonlijk en de afspraken duidelijk.</p><a href="/over-ons" className="text-accent font-bold inline-flex gap-2 items-center">Maak kennis met WeDeploy <ArrowRight size={16} /></a></div></div></Section>
    <Section><div className="mb-8"><p className="eyebrow">Vast of tijdelijk</p><h2 className="section-title">De inzet die bij jouw vraag past.</h2></div><div className="grid sm:grid-cols-2 gap-5">{services.map(service => <article className="content-card" key={service.id}><h3 className="text-xl font-bold text-primary mb-3">{service.title}</h3><p className="text-muted-foreground leading-relaxed">{service.description}</p><a href={`/expertise-diensten#${service.id}`} className="inline-flex items-center gap-2 text-accent text-sm font-bold mt-5">Meer over {service.title.toLowerCase()} <ArrowRight size={15} /></a></article>)}</div></Section>
    <Section navy><div className="grid md:grid-cols-2 gap-10 items-center"><div><p className="eyebrow">Exclusieve werving & selectie</p><h2 className="text-3xl md:text-4xl font-bold tracking-tight">Eén zoektocht. Volle aandacht.</h2><p className="mt-5 text-white/75 leading-relaxed">Voor een belangrijke vacature wil je een gerichte aanpak. Met een exclusieve zoekopdracht geven we die zoektocht samen de aandacht die nodig is.</p></div><div><ul className="space-y-4 text-white/85">{["Een profiel dat we samen scherpstellen", "Actieve benadering van passende professionals", "Persoonlijke gesprekken vóór een introductie", "Duidelijke updates over voortgang en reacties"].map(text => <li key={text} className="flex gap-3"><Check className="text-accent shrink-0" size={20} />{text}</li>)}</ul><div className="mt-7"><ActionLink href="/contact?type=opdrachtgever&onderwerp=Exclusieve%20zoekopdracht">Bespreek een zoekopdracht</ActionLink></div></div></div></Section>
    <Section><p className="eyebrow">Zo werken we</p><h2 className="section-title mb-8">Van een goede vraag naar een passende collega.</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{[
      ["01", "Eerst begrijpen", "We bespreken de functie, het team, de voorwaarden en wat iemand moet bereiken."],
      ["02", "Gericht zoeken", "We kijken in ons netwerk en benaderen professionals die bij jouw vraag passen."],
      ["03", "Persoonlijk selecteren", "We spreken kandidaten en bespreken ervaring, motivatie en praktische verwachtingen."],
      ["04", "Zorgvuldig starten", "We begeleiden de kennismaking en afspraken. Ook na de start houden we contact."],
    ].map(([n, title, text]) => <article key={n}><span className="text-accent font-bold text-sm">{n}</span><h3 className="text-lg font-bold text-primary mt-3 mb-3">{title}</h3><p className="text-muted-foreground text-sm leading-relaxed">{text}</p></article>)}</div></Section>
    <FAQ items={employerFAQ} /><ClosingCTA title="Een vacature of opdracht bespreken?" text="Ook als het profiel nog niet helemaal duidelijk is. We denken graag mee over wie je nodig hebt." label="Neem contact op" href="/contact?type=opdrachtgever" />
  </PageLayout>;
}
export function Professionals() {
  return <PageLayout label="Beschikbare professionals" title="Een netwerk met verstand van jouw werk." intro="We kennen zelfstandige en vaste professionals binnen vastgoed, facility, projecten en techniek. Hieronder vind je een indruk van hun expertise. We bespreken graag wie bij jouw vraag past." cta="Vraag naar een professional" ctaHref="/contact?type=opdrachtgever">
    <Section><ProfessionalCards /><p className="text-sm text-muted-foreground leading-relaxed mt-7 max-w-3xl">Deze omschrijvingen geven een beeld van de rollen in ons netwerk. Namen en cv’s delen we na afstemming. Beschikbaarheid, ervaring en inzetvorm bespreken we per aanvraag.</p></Section>
    <ClosingCTA title="Staat jouw vraag er niet tussen?" text="Vertel ons welk werk gedaan moet worden. We zoeken ook gericht buiten ons bestaande netwerk." label="Bespreek jouw vraag" href="/contact?type=opdrachtgever" />
  </PageLayout>;
}
export function Vacancies() {
  return <PageLayout label="Vacatures & opdrachten" title="Wat wordt jouw volgende stap?" intro="Een vaste baan, een nieuwe interim opdracht of eerst eens kennismaken. Vertel ons waar je goed in bent en wat je zoekt. Dan kijken we samen naar passende mogelijkheden." cta="Stuur jouw cv" ctaHref="#inschrijven">
    <Section><VacancyCards /><div className="mt-10 grid md:grid-cols-2 gap-8"><div><h2 className="section-title">Jouw ervaring. Jouw volgende stap.</h2><p className="mt-5 text-muted-foreground leading-relaxed">We bemiddelen binnen vastgoed, Facility Management, projectmanagement, PMO en techniek. Van projectondersteuning tot leidinggevende en specialistische rollen.</p></div><div className="content-card"><h3 className="text-xl font-bold text-primary mb-3">Ook zonder concrete vacature welkom.</h3><p className="text-muted-foreground leading-relaxed">Laat weten welke functie of opdracht je zoekt, in welke regio en voor hoeveel uur. Ook als je nu goed zit en alleen openstaat voor iets dat echt past.</p><a href="/expertise-diensten" className="text-accent font-bold inline-flex gap-2 mt-5 items-center">Bekijk onze vakgebieden <ArrowRight size={16} /></a></div></div></Section>
    <div id="inschrijven"><ContactSection defaultRole="kandidaat" heading="Vertel ons wat je zoekt." context="Open inschrijving" /></div>
  </PageLayout>;
}
export function ExpertiseServices() {
  return <PageLayout label="Expertise & diensten" title="De juiste mensen voor gebouwen, teams en projecten." intro="WeDeploy brengt opdrachtgevers en professionals bij elkaar binnen vier vakgebieden. Voor een vaste aanstelling, tijdelijke versterking of een specialistische opdracht." cta="Ik zoek versterking" ctaHref="/contact?type=opdrachtgever" secondary={{ label: "Ik zoek een volgende stap", href: "/vacatures#inschrijven" }}>
    <Section><p className="eyebrow">Onze vakgebieden</p><h2 className="section-title mb-8">Werk dat we begrijpen.</h2><div className="grid md:grid-cols-2 gap-5">{expertise.map(area => <article id={area.id} key={area.id} className="content-card"><h3 className="text-2xl font-bold text-primary mb-4">{area.title}</h3><p className="text-muted-foreground leading-relaxed">{area.description}</p><p className="text-sm leading-relaxed text-primary/80 border-t border-border mt-5 pt-5">{area.roles}</p></article>)}</div></Section>
    <Section><p className="eyebrow">Manieren van samenwerken</p><h2 className="section-title mb-8">Een passende vorm voor beide kanten.</h2><div className="grid md:grid-cols-2 gap-5">{services.map(service => <article id={service.id} className="content-card" key={service.id}><h3 className="text-2xl font-bold text-primary mb-4">{service.title}</h3><p className="text-muted-foreground leading-relaxed">{service.description}</p><p className="text-sm leading-relaxed text-primary/80 border-t border-border mt-5 pt-5">{service.audience}</p></article>)}</div></Section>
    <ClosingCTA title="Wat past bij jouw situatie?" text="We bespreken de mogelijkheden en maken vooraf heldere afspraken over de samenwerking." />
  </PageLayout>;
}
export function About() {
  return <PageLayout label="Over WeDeploy" title="Goed recruiten begint met het werk begrijpen." intro="WeDeploy is opgericht door Nicky Verkooij. Vanuit jarenlange ervaring in Facility Management en vastgoed helpt hij organisaties en professionals aan een passende samenwerking." cta="Maak kennis met Nicky" ctaHref="/contact">
    <Section><div className="grid md:grid-cols-[0.8fr_1.2fr] gap-10 md:gap-16 items-center"><div className="rounded-2xl bg-white border border-border overflow-hidden"><img src={nickPhoto} alt="Nicky Verkooij, oprichter van WeDeploy" width="600" height="700" className="w-full max-h-[480px] object-cover object-top" loading="lazy" /></div><div><p className="eyebrow">Nicky Verkooij · Oprichter</p><h2 className="section-title">De praktijk als vertrekpunt.</h2><div className="mt-6 space-y-4 text-muted-foreground leading-relaxed"><p>Ik heb zelf teams geleid, vastgoed beheerd en huisvestingsprojecten begeleid. Daardoor weet ik hoe belangrijk het is dat iemand niet alleen de juiste ervaring heeft, maar ook past bij het team en het werk dat er ligt.</p><p>Met WeDeploy verbind ik die praktijkervaring aan recruitment. Ik neem de tijd om een vraag te begrijpen, spreek professionals persoonlijk en maak duidelijk waarom ik iemand voorstel.</p><p>Je hebt rechtstreeks contact met mij. Over jouw vacature, een volgende opdracht of de samenwerking na een start.</p></div><div className="mt-7"><ActionLink href="/contact">Laten we kennismaken</ActionLink></div></div></div></Section>
    <Section><div className="grid md:grid-cols-3 gap-5">{[["Inhoudelijk betrokken", "We bespreken wat iemand moet kunnen én wat de organisatie nodig heeft."], ["Persoonlijk contact", "Korte lijnen, eerlijke terugkoppeling en ruimte om vragen te stellen."], ["Duidelijke afspraken", "Vooraf weten waar je aan toe bent. Over inzet, verwachtingen en voorwaarden."]].map(([title,text]) => <article className="content-card" key={title}><h2 className="text-xl font-bold text-primary mb-3">{title}</h2><p className="text-muted-foreground leading-relaxed">{text}</p></article>)}</div></Section>
    <ClosingCTA />
  </PageLayout>;
}
export function Contact() {
  return <PageLayout label="Contact" title="Vertel ons wat je zoekt." intro="Een professional nodig of toe aan een volgende stap? Neem rechtstreeks contact op met Nicky. Een eerste gesprek is vrijblijvend.">
    <Section><div className="flex flex-wrap gap-5"><a href="tel:+31852128668" className="content-card inline-flex gap-3 items-center font-bold text-primary"><Phone className="text-accent" size={22} />085 212 8668</a><a href="mailto:info@wedeploy.nl" className="content-card inline-flex gap-3 items-center font-bold text-primary"><Mail className="text-accent" size={22} />info@wedeploy.nl</a></div></Section><ContactSection heading="Waar kunnen we je bij helpen?" readQuery />
  </PageLayout>;
}
export function Privacy() {
  return <PageLayout label="Privacy" title="Zorgvuldig met jouw gegevens." intro="Wanneer je contact opneemt of een cv instuurt, gebruik je persoonsgegevens. Hieronder lees je waarvoor WeDeploy die gegevens gebruikt.">
    <Section><div className="max-w-3xl space-y-8 text-muted-foreground leading-relaxed">{[
      ["Welke gegevens ontvangen we?", "Via het formulier ontvangen we jouw naam, e-mailadres, eventueel telefoonnummer, bericht en het cv dat je zelf uploadt. Bij een aanvraag kan ook een functietitel of profielreferentie worden meegestuurd."],
      ["Waarvoor gebruiken we die gegevens?", "We gebruiken ze om jouw vraag te beantwoorden, contact te onderhouden en een mogelijke samenwerking of sollicitatie te bespreken. We delen een herkenbaar kandidaatprofiel of cv met een mogelijke opdrachtgever pas na afstemming met jou."],
      ["Hoe worden gegevens verwerkt?", "De website wordt gehost via Vercel. Formulierberichten en eventuele cv-bijlagen worden via Resend naar de mailbox van WeDeploy gestuurd. We beperken toegang tot de gegevens tot wie die nodig heeft voor de behandeling van jouw vraag."],
      ["Hoe lang bewaren we gegevens?", "We bewaren gegevens niet langer dan nodig voor het contact, de sollicitatie of de afgesproken samenwerking. Willen we jouw cv ook voor toekomstige mogelijkheden bewaren, dan bespreken we dat met je."],
      ["Jouw gegevens inzien of verwijderen", "Wil je weten welke gegevens we van je hebben, iets aanpassen of jouw cv laten verwijderen? Mail naar info@wedeploy.nl. Je kunt daar ook vragen stellen over deze verklaring."],
      ["Cookies", "Deze website gebruikt in de huidige versie geen advertentie- of analysetrackers. Als we die toevoegen, passen we deze informatie en eventuele toestemmingsinstellingen aan."],
    ].map(([title,text]) => <section key={title}><h2 className="text-xl font-bold text-primary mb-3">{title}</h2><p>{text}</p></section>)}</div></Section>
  </PageLayout>;
}
