import { PageLayout, Section, FAQ } from "@/components/PageLayout";
import { EditorialSection, StatementSection } from "@/components/PageSections";
import { ContactSection } from "@/components/ContactSection";
export function FlexibleWorkPage({ candidate = false }: { candidate?: boolean }) {
  const label = candidate ? "Zzp-opdrachten" : "Interim professionals";
  return <PageLayout label={label} variant={candidate ? "editorial" : "navy"} hero={candidate ? "paper" : "type"} title={candidate ? "Zzp-opdrachten" : "Interim professionals"} intro={candidate ? "Zelfstandig in projectmanagement, Facility Management, vastgoed of techniek? Deel jouw ervaring en beschikbaarheid. We bespreken welke opdracht bij jouw expertise past." : "Een project dat regie nodig heeft, tijdelijke leiding of specialistische kennis. We zoeken een interim professional die het werk kan oppakken."} cta={candidate ? "Deel jouw beschikbaarheid" : "Bespreek jouw opdracht"} ctaHref="#contact">
    <EditorialSection eyebrow={candidate ? "Voor zelfstandigen" : "Voor opdrachtgevers"} title={candidate ? "Een opdracht die jouw ervaring benut" : "De opdracht als vertrekpunt"} offset><p>{candidate ? "Een goede opdracht sluit aan op jouw expertise, manier van werken en ambities. Daarom leren we jou eerst kennen. We bespreken eerdere opdrachten, de verantwoordelijkheid die je zoekt en de omgeving waarin je wilt werken. Of je nu een project wilt leiden, tijdelijk een team aanstuurt of specialistische kennis meebrengt." : "We bespreken wat er moet gebeuren, welk resultaat je verwacht en welke beslisruimte de professional krijgt. Ook looptijd, uren en aanwezigheid op locatie horen bij het zoekprofiel."}</p><p>{candidate ? "We nemen contact met je op om een persoonlijke intake te plannen. Dat kan ook als je huidige opdracht nog loopt. We bespreken jouw ervaring, wensen en beschikbaarheid." : "Niet iedere tijdelijke rol past bij zelfstandige inzet. We bekijken de aard van het werk en bespreken detachering als dat beter aansluit."}</p></EditorialSection>
    <StatementSection eyebrow="Vooraf afstemmen" title={candidate ? "Dit bespreken we met je." : "Een inhoudelijke introductie."} dark={!candidate}><p>{candidate ? "Relevante projecten, beschikbaarheid, regio, gewenste inzet en tariefindicatie. Bij een mogelijke opdracht stemmen we de inhoud en voorwaarden met je af voordat we je voorstellen." : "We spreken professionals over relevante opdrachten, aanpak en beschikbaarheid. Bij een voorstel lichten we toe waar de ervaring aansluit en welke aandachtspunten je samen moet bespreken."}</p></StatementSection>
    <EditorialSection eyebrow="Van kennismaking naar opdracht" title="Eerst de inhoud, daarna de afspraken" tone="white"><p>In de intake bespreken we jouw eerdere opdrachten, aanpak en de verantwoordelijkheid die je zoekt. Een volgende opdracht hoeft niet hetzelfde te zijn als de vorige. Vertel ook welke omgeving je aanspreekt en wat je wilt blijven doen.</p><p>Is er een concrete mogelijkheid, dan bespreken we het resultaat, de looptijd, inzet, locatie en voorwaarden. Je hoort welke informatie al bekend is en welke vragen nog openstaan. We stellen je alleen voor als jij daarachter staat.</p><p>Voor de start stemmen we af wie jouw opdrachtgever en aanspreekpunt zijn en hoe de samenwerking wordt vastgelegd. We houden contact over de voortgang en eventuele veranderingen tijdens de opdracht.</p></EditorialSection><Section tone="white"><p className="eyebrow">Projectmanagement en meer</p><h2 className="section-title mb-5">Expertise voor de praktijk.</h2><div className="landing-directory-links">{[["Projectmanagement & PMO", "/werken-in-projectmanagement"], ["Facility Management", "/werken-in-facility-management"], ["Vastgoed & huisvesting", "/werken-in-vastgoed"], ["Gebouwgebonden techniek", "/technisch-beheer"]].map(([name, path]) => <a key={path} href={path} className="action-arrow font-bold text-primary">{name}</a>)}</div><p className="mt-5 text-muted-foreground leading-relaxed">{candidate ? "Zoek je een andere functie? Stuur gerust je cv en vertel wat je zoekt." : "We bespreken ook aanvragen buiten deze vakgebieden. We geven vooraf aan of de expertise bij Wedeploy past."}</p></Section>
    <FAQ items={candidate ? [{ question: "Kan ik mijn cv sturen zonder concrete opdracht?", answer: "Ja. Vertel welke rol je zoekt en wanneer je beschikbaar bent. We nemen contact met je op om een persoonlijke intake te plannen, ook zonder concrete opdracht." }, { question: "Wordt mijn cv doorgestuurd?", answer: "Niet zonder jouw toestemming. We bespreken eerst de functie of opdracht en stellen je alleen voor als jij daarmee akkoord bent." }] : [{ question: "Wat hebben jullie nodig om iemand te zoeken?", answer: "Een korte uitleg van het werk, het gewenste resultaat, de looptijd en startdatum is genoeg. We werken de verantwoordelijkheden, uren en voorwaarden samen uit." }, { question: "Interim of detachering?", answer: "Bij detachering is de professional in dienst bij Wedeploy en werkt die tijdelijk bij jou. Interim beschrijft tijdelijke inzet; dat kan bijvoorbeeld een zzp-opdracht zijn. We kijken welke vorm aansluit op het werk." }]} />
    <ContactSection compact lockRole defaultRole={candidate ? "kandidaat" : "opdrachtgever"} context={label} readQuery heading={candidate ? "Laat je cv achter." : "Vertel wat er moet gebeuren."} description={candidate ? "Vertel welke rol je zoekt, waar je wilt werken en wanneer je beschikbaar bent. We nemen contact met je op om een persoonlijke intake te plannen." : "Een eerste omschrijving van het werk, de gewenste inzet en startdatum is genoeg. We werken de vraag samen verder uit."} />
  </PageLayout>;
}
