import { PageLayout, Section, FAQ } from "@/components/PageLayout";
import { EditorialSection, StatementSection } from "@/components/PageSections";
import { ContactSection } from "@/components/ContactSection";
export function FlexibleWorkPage({ candidate = false }: { candidate?: boolean }) {
  const label = candidate ? "Zzp-opdrachten" : "Interim professionals";
  return <PageLayout label={label} variant={candidate ? "editorial" : "navy"} hero={candidate ? "paper" : "type"} title={candidate ? "Zelfstandig en toe aan een nieuwe opdracht?" : "Tijdelijk nodig. Gericht gezocht."} intro={candidate ? "Zelfstandig in projectmanagement, Facility Management, vastgoed of techniek? Deel jouw ervaring en beschikbaarheid. We bespreken welke opdracht bij jouw expertise past." : "Een project dat regie nodig heeft, tijdelijke leiding of specialistische kennis. We zoeken een interim professional die het werk kan oppakken."} cta={candidate ? "Deel jouw beschikbaarheid" : "Bespreek jouw opdracht"} ctaHref="#contact">
    <EditorialSection eyebrow={candidate ? "Voor zelfstandigen" : "Voor opdrachtgevers"} title={candidate ? "Waar maak jij het verschil?" : "De opdracht als vertrekpunt."} offset><p>{candidate ? "Vertel wat je hebt gedaan en welk werk je wilt oppakken. Een project leiden, een team tijdelijk aansturen of een specialistische vraag oplossen: jouw ervaring bepaalt de richting." : "We bespreken wat er moet gebeuren, welk resultaat je verwacht en welke beslisruimte de professional krijgt. Ook looptijd, uren en aanwezigheid op locatie horen bij het zoekprofiel."}</p><p>{candidate ? "Een kennismaking kan ook als je nu nog een opdracht hebt. Geef aan wanneer je weer beschikbaar bent." : "Niet iedere tijdelijke rol past bij zelfstandige inzet. We bekijken de aard van het werk en bespreken detachering als dat beter aansluit."}</p></EditorialSection>
    <StatementSection eyebrow="Vooraf afstemmen" title={candidate ? "Dit bespreken we met je." : "Een inhoudelijke introductie."} dark={!candidate}><p>{candidate ? "Relevante projecten, beschikbaarheid, regio, gewenste inzet en tariefindicatie. Bij een mogelijke opdracht stemmen we de inhoud en voorwaarden met je af voordat we je voorstellen." : "We spreken professionals over relevante opdrachten, aanpak en beschikbaarheid. Bij een voorstel lichten we toe waar de ervaring aansluit en welke aandachtspunten je samen moet bespreken."}</p></StatementSection>
    <Section tone="white"><p className="eyebrow">Projectmanagement en meer</p><h2 className="section-title mb-5">Expertise voor de praktijk.</h2><div className="landing-directory-links">{[["Projectmanagement & PMO", "/werken-in-projectmanagement"], ["Facility Management", "/werken-in-facility-management"], ["Vastgoed & huisvesting", "/werken-in-vastgoed"], ["Gebouwgebonden techniek", "/technisch-beheer"]].map(([name, path]) => <a key={path} href={path} className="font-bold text-primary">{name}</a>)}</div><p className="mt-5 text-muted-foreground leading-relaxed">{candidate ? "Zoek je een andere functie? Stuur gerust je cv en vertel wat je zoekt." : "We bespreken ook aanvragen buiten deze vakgebieden. We geven vooraf aan of de expertise bij Wedeploy past."}</p></Section>
    <FAQ items={candidate ? [{ question: "Kan ik mijn cv sturen zonder concrete opdracht?", answer: "Ja. Vertel welke rol je zoekt en wanneer je beschikbaar bent. We nemen contact op als we je ervaring verder willen bespreken of een passende mogelijkheid zien." }, { question: "Wordt mijn cv doorgestuurd?", answer: "Niet zonder jouw toestemming. We bespreken eerst de functie of opdracht en stellen je alleen voor als jij daarmee akkoord bent." }] : [{ question: "Wat hebben jullie nodig om iemand te zoeken?", answer: "Een korte uitleg van het werk, het gewenste resultaat, de looptijd en startdatum is genoeg. We werken de verantwoordelijkheden, uren en voorwaarden samen uit." }, { question: "Interim of detachering?", answer: "Bij detachering is de professional in dienst bij Wedeploy en werkt die tijdelijk bij jou. Interim beschrijft tijdelijke inzet; dat kan bijvoorbeeld een zzp-opdracht zijn. We kijken welke vorm aansluit op het werk." }]} />
    <ContactSection compact lockRole defaultRole={candidate ? "kandidaat" : "opdrachtgever"} context={label} readQuery heading={candidate ? "Laat je cv achter." : "Vertel wat er moet gebeuren."} description={candidate ? "Vertel welke rol je zoekt, waar je wilt werken en wanneer je beschikbaar bent. Dan bespreken we of jouw profiel aansluit op een vraag." : "Een eerste omschrijving van het werk, de gewenste inzet en startdatum is genoeg. We werken de vraag samen verder uit."} />
  </PageLayout>;
}
