import { PageLayout, Section, ActionLink, FAQ } from "@/components/PageLayout";
import { ContactSection } from "@/components/ContactSection";
export function FlexibleWorkPage({ candidate = false }: { candidate?: boolean }) {
  const label = candidate ? "Zzp-opdrachten" : "Interim professionals";
  return <PageLayout label={label} variant={candidate ? "editorial" : "navy"} hero={candidate ? "paper" : "type"} title={candidate ? "Jouw expertise. Een nieuwe opdracht." : "Tijdelijk nodig. Gericht gezocht."} intro={candidate ? "Zelfstandig in projectmanagement, Facility Management, vastgoed of techniek? Deel jouw ervaring en beschikbaarheid. We bespreken welke opdracht bij jouw expertise past." : "Een project dat regie nodig heeft, tijdelijke leiding of specialistische kennis. We zoeken een interim professional die het werk kan oppakken."} cta={candidate ? "Deel jouw beschikbaarheid" : "Bespreek jouw opdracht"} ctaHref="#contact">
    <Section><div className="grid md:grid-cols-2 gap-6 md:gap-12"><div><p className="eyebrow">{candidate ? "Voor zelfstandigen" : "Voor opdrachtgevers"}</p><h2 className="section-title">{candidate ? "Waar maak jij het verschil?" : "De opdracht als vertrekpunt."}</h2><p className="mt-4 text-muted-foreground leading-relaxed">{candidate ? "Vertel wat je hebt gedaan en welk werk je wilt oppakken. Een project leiden, een team tijdelijk aansturen of een specialistische vraag oplossen: jouw ervaring bepaalt de richting." : "We bespreken wat er moet gebeuren, welk resultaat je verwacht en welke beslisruimte de professional krijgt. Ook looptijd, uren en aanwezigheid op locatie horen bij het zoekprofiel."}</p></div><div><h3 className="text-xl font-bold text-primary">{candidate ? "Dit bespreken we met je." : "Een inhoudelijke introductie."}</h3><p className="mt-4 text-muted-foreground leading-relaxed">{candidate ? "Relevante projecten, beschikbaarheid, regio, gewenste inzet en tariefindicatie. Bij een mogelijke opdracht stemmen we de inhoud en voorwaarden met je af voordat we je voorstellen." : "We spreken professionals over relevante opdrachten, aanpak en beschikbaarheid. Bij een voorstel lichten we toe waar de ervaring aansluit en welke aandachtspunten je samen moet bespreken."}</p><p className="mt-4 text-muted-foreground leading-relaxed">{candidate ? "Een kennismaking kan ook als je nu nog een opdracht hebt. Geef aan wanneer je weer beschikbaar bent." : "Niet iedere tijdelijke rol past bij zelfstandige inzet. We bekijken de aard van het werk en bespreken detachering als dat beter aansluit."}</p></div></div></Section>
    <Section tone="white"><p className="eyebrow">Projectmanagement en meer</p><h2 className="section-title mb-5">Expertise voor de praktijk.</h2><div className="landing-directory-links">{[["Projectmanagement & PMO", "/interim-projectmanagement"], ["Facility Management", "/facility-management"], ["Vastgoed & huisvesting", "/vastgoed"], ["Techniek & installaties", "/expertise-diensten#techniek"]].map(([name, path]) => <a key={path} href={path} className="font-bold text-primary">{name}</a>)}</div><p className="mt-5 text-muted-foreground leading-relaxed">{candidate ? "Dit zijn onze belangrijkste vakgebieden. Je kunt ook met andere specialistische ervaring contact opnemen." : "Het werk bepaalt welke expertise nodig is. We bespreken ook aanvragen buiten deze vakgebieden."}</p></Section>
    <FAQ items={candidate ? [{ question: "Kan ik alvast kennismaken?", answer: "Ja. Deel jouw cv, expertise en beschikbaarheid. Je hoeft niet te wachten op een gepubliceerde opdracht." }, { question: "Wordt mijn cv gedeeld?", answer: "We bespreken een concrete opdracht en mogelijke introductie eerst met jou. Een herkenbaar profiel of cv delen we pas na afstemming." }] : [{ question: "Hoe snel kan iemand starten?", answer: "Dat hangt af van de opdracht en de beschikbaarheid van passende professionals. Geef jouw gewenste startdatum door; we bespreken wat haalbaar is." }, { question: "Interim of detachering?", answer: "Bij interim bemiddelen we een zelfstandige professional voor een opdracht. Bij detachering werkt de professional in loondienst via Wedeploy. De inhoud en inrichting van het werk bepalen welke vorm past." }]} />
    <Section><div className="flex flex-wrap gap-5"><ActionLink href={candidate ? "/interim-opdrachten-amsterdam" : "/interim-amsterdam"} secondary>{candidate ? "Zzp & interim in Amsterdam" : "Interim in Amsterdam"}</ActionLink><ActionLink href={candidate ? "/interim-professionals" : "/zzp-opdrachten"} secondary>{candidate ? "Voor opdrachtgevers" : "Voor zelfstandigen"}</ActionLink></div></Section>
    <ContactSection compact lockRole defaultRole={candidate ? "kandidaat" : "opdrachtgever"} context={label} heading={candidate ? "Deel jouw cv." : "Vertel wat er moet gebeuren."} />
  </PageLayout>;
}
