import { PageLayout, Section, ActionLink, FAQ } from '@/components/PageLayout';
import { functionPages, functionGroups, functionIndexImage, roleContact, roleIntake } from '@/data/functions';
import NotFound from '@/pages/not-found';

export function FunctionIndex() {
  return <div className="function-shell"><PageLayout label="Functies" title="Welk werk past bij jou?" intro="Een functietitel vertelt niet het hele verhaal. Ontdek wat het werk inhoudt, welke ervaring erbij past en waar de rollen van elkaar verschillen." photo={functionIndexImage}>
    <Section tone="white"><div className="function-index-intro"><h2>Van projectleiding tot dagelijkse ondersteuning</h2><p>Dit zijn functies binnen de vakgebieden waarin we bemiddelen. Zoek je zelf werk of iemand voor jouw organisatie? De uitleg helpt om jouw vraag concreet te maken.</p></div><nav className="function-group-nav" aria-label="Kies een vakgebied">{functionGroups.map(group => <a key={group.key} href={`#${group.key}`}>{group.label}</a>)}</nav></Section>
    {functionGroups.map((group, index) => <Section key={group.key} id={group.key} tone={index % 2 ? 'white' : 'plain'} className="function-index-group"><header><h2>{group.label}</h2><p>{group.intro}</p></header><ul className="function-index-list">{functionPages.filter(role => role.group === group.key).map(role => <li key={role.slug}><h3><a className="action-arrow" href={role.path}>{role.title}</a></h3><p>{role.intro}</p></li>)}</ul></Section>)}
    <Section tone="wash"><div className="function-index-closing"><div><h2>Jouw functie niet gevonden?</h2><p>Vertel welk werk je zoekt of welke versterking je nodig hebt. We bespreken graag of we daarbij kunnen helpen.</p></div><ActionLink href="/contact">Neem contact op</ActionLink></div></Section>
  </PageLayout></div>;
}

/** All function pages share hero, reading rhythm, audience routes, FAQ and internal links. */
export function FunctionDetail({ slug }: { slug: string }) {
  const role = functionPages.find(item => item.slug === slug);
  if (!role) return <NotFound />;
  const group = functionGroups.find(item => item.key === role.group)!;
  const related = role.related.map(value => functionPages.find(item => item.slug === value)).filter(item => item !== undefined);
  return <div className="function-shell"><PageLayout label={role.title} title={role.heading} intro={role.intro} photo={role.image} breadcrumbs={[{ label: 'Functies', href: '/functies' }]} cta="Ik zoek een professional" ctaHref={roleContact(role)} secondary={{ label: 'Ik zoek werk', href: roleIntake(role) }}>
    <Section tone="white"><div className="function-reading"><section id="de-rol"><p className="function-kicker">{group.label}</p><h2>De rol in de praktijk</h2>{role.definition.map(text => <p key={text}>{text}</p>)}</section><nav className="function-section-nav" aria-label="In deze functie"><a href="#werkzaamheden">Werkzaamheden</a><a href="#ervaring">Ervaring</a><a href="#via-wedeploy">Vast of tijdelijk</a></nav></div></Section>
    <Section tone="plain"><div className="function-task-composition"><header><p className="function-kicker">Werkzaamheden</p><h2>Wat hoort bij het werk?</h2><p>Het takenpakket hangt af van de organisatie en de verantwoordelijkheid van de functie.</p></header><ul id="werkzaamheden">{role.tasks.map(task => <li key={task}>{task}</li>)}</ul><aside className="function-practice"><p className="function-kicker">Praktijkvoorbeeld</p><h3>{role.practice.title}</h3><p>{role.practice.text}</p></aside></div></Section>
    <Section tone="white"><div className="function-reading"><section><h2>Waar werk je?</h2><p>{role.environment}</p><a className="action-arrow function-inline-link" href={group.path}>Meer over {group.label}</a></section><section id="ervaring"><h2>Welke achtergrond past erbij?</h2><p>{role.background}</p><h3 className="function-selection-title">Waar let je op bij deze functie?</h3><ul className="function-selection">{role.selection.map(item => <li key={item}>{item}</li>)}</ul></section><section><h2>{role.difference.title}</h2><p>{role.difference.text}</p></section></div></Section>
    <Section tone="wash" id="via-wedeploy"><div className="function-audience-heading"><h2>Deze functie via Wedeploy</h2><p>Wij verbinden organisaties en professionals voor vaste functies en tijdelijke opdrachten.</p></div><div className="function-audience-grid"><article><p className="function-kicker">Voor opdrachtgevers</p><h3>Versterking voor jouw organisatie</h3><p>{role.employer}</p><p>We verdiepen ons in de functie en jouw organisatie. Zo zoeken we gericht naar iemand die inhoudelijk én als persoon past.</p><ActionLink href={roleContact(role)}>Bespreek jouw vacature</ActionLink><a className="action-arrow function-inline-link" href="/professionals">Bekijk ons netwerk</a></article><article><p className="function-kicker">Voor professionals</p><h3>Een volgende stap die bij je past</h3><p>{role.candidate}</p><p>Laat je cv achter. We nemen contact met je op voor een persoonlijke intake over jouw ervaring, wensen en ambities.</p><ActionLink href={roleIntake(role)}>Laat jouw cv achter</ActionLink><a className="action-arrow function-inline-link" href="/vacatures">Bekijk vacatures & opdrachten</a></article></div>
      <div className="function-engagement"><p>Bij werving & selectie treedt de professional in dienst bij de opdrachtgever. Bij detachering is Wedeploy de werkgever. Interim gaat over tijdelijke inzet; de opdracht kan via detachering of, waar passend, als zzp-opdracht worden ingevuld.</p><nav aria-label="Manieren van samenwerken"><a className="action-arrow" href="/werving-selectie">Werving & selectie</a><a className="action-arrow" href="/detachering">Detachering & detavast</a><a className="action-arrow" href="/interim-zzp">Interim & zzp</a></nav></div>
    </Section>
    <Section tone="white"><div className="function-reading function-further"><section><h2>Verwante functies</h2><ul>{related.map(item => <li key={item.slug}><a className="action-arrow" href={item.path}>{item.title}</a></li>)}</ul><a className="action-arrow function-inline-link" href="/functies">Bekijk alle functies</a></section><section><h2>Goed om te weten</h2><ul><li><a className="action-arrow" href="/kennisbank/detachering-interim-werving-selectie">Detachering, interim of werving & selectie?</a></li><li><a className="action-arrow" href="/kennisbank/werken-via-detachering">Werken via detachering</a></li></ul></section>{role.sources?.length && <section className="function-sources"><h2>Verdiep je in het vak</h2><ul>{role.sources.map(source => <li key={source.href}><a href={source.href}>{source.label}</a></li>)}</ul></section>}</div></Section>
    <FAQ items={role.faq} />
  </PageLayout></div>;
}
