import { vakgebieden, type VakgebiedKey } from '@/data/vakgebieden';
import { PageLayout, Section, ActionLink, FAQ, ClosingCTA } from '@/components/PageLayout';
import { EditorialSection, StatementSection } from '@/components/PageSections';
import { VacancyCards } from '@/components/VacancyCards';
export function SectorPage({ sector, candidate = false }: {sector: VakgebiedKey; candidate?: boolean}) {
  const page = vakgebieden[sector];
  const query = `/contact?type=opdrachtgever&onderwerp=${encodeURIComponent(page.label)}#contact`;
  const signUp = `/vacatures?type=kandidaat&onderwerp=${encodeURIComponent(page.label)}#inschrijven`;
  const candidateLabel = sector === 'projecten' ? 'Werken in projectmanagement & PMO' : sector === 'facility' ? 'Werken in Facility Management' : 'Werken in vastgoed';
  if (candidate) return <PageLayout label={candidateLabel} title={sector === 'projecten' ? 'Werken in projectmanagement' : candidateLabel} intro={page.candidateIntro} variant="editorial" cta="Laat jouw cv achter" ctaHref={signUp} secondary={{label:'Bekijk vacatures & opdrachten',href:'#mogelijkheden'}}>
    <EditorialSection eyebrow="Voor professionals" title={page.candidateHeading}>{page.candidateParagraphs.map(text => <p key={text}>{text}</p>)}</EditorialSection>
    <Section tone="white"><p className="eyebrow">Functies binnen dit vakgebied</p><h2 className="section-title">Welke rol past bij jou?</h2><p className="section-lead">Je kunt op verschillende manieren bijdragen. Bekijk de rollen hieronder en vertel welke werkzaamheden en verantwoordelijkheid jij zoekt.</p><div className="role-directory mt-7">{page.roles.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
    <EditorialSection eyebrow="Persoonlijke intake" title="Eerst leren we jou kennen."><p>{page.candidateFit}</p><p>Na jouw reactie nemen we contact op om een intake te plannen. We bespreken jouw motivatie, wensen en ambities, naast uren, regio, beschikbaarheid en voorwaarden. Zoek je een vaste baan, dan kijken we naar werving & selectie of een start via detachering. Voor zelfstandig professionals bespreken we concrete opdrachten en de afspraken over de inzet.</p><p>Bij een mogelijke introductie hoor je eerst meer over het werk, de organisatie en het team. We bespreken jouw interesse en delen je cv pas nadat jij akkoord bent. Een intake kan ook zonder openstaande vacature. Het betekent niet dat er direct een passende functie beschikbaar is.</p></EditorialSection>
    <Section id="mogelijkheden" tone="white"><p className="eyebrow">Actuele mogelijkheden</p><h2 className="section-title mb-6">Vacatures & opdrachten.</h2><VacancyCards emptyVariant="listing" sector={sector} /><div className="mt-6 flex flex-wrap gap-x-6 gap-y-2"><ActionLink href="/vacatures">Bekijk alle vacatures</ActionLink><ActionLink secondary href={signUp}>Laat jouw cv achter</ActionLink></div></Section>
    <FAQ items={[{question:'Kan ik reageren zonder openstaande vacature?',answer:'Ja. Stuur jouw cv en een korte toelichting op de functie of opdracht die je zoekt. We nemen contact met je op om een persoonlijke intake te plannen.'},{question:'Kan ik vast én tijdelijk werken?',answer:'Dat hangt af van de functie of opdracht. We bespreken werving & selectie, detachering en zelfstandige inzet. De voorwaarden en verwachtingen maken we duidelijk voordat je kiest.'}]} />
    <ClosingCTA title="Toe aan een volgende stap?" text="Deel jouw ervaring en vertel welk werk je zoekt. We nemen contact met je op om een persoonlijke intake te plannen." label="Laat jouw cv achter" href={signUp} />
  </PageLayout>;
  return <PageLayout label={page.label} title={sector === 'techniek' ? 'Technisch beheer' : page.label} intro={page.intro} variant={sector === 'vastgoed' ? 'split' : 'editorial'} cta="Bespreek jouw personeelsvraag" ctaHref={query} secondary={{label:'Ik zoek werk',href:page.candidatePath}}>
    <EditorialSection eyebrow="Voor opdrachtgevers" title={page.heading}>{page.paragraphs.map(text => <p key={text}>{text}</p>)}</EditorialSection>
    <Section tone="white"><p className="eyebrow">Herkenbare situaties</p><h2 className="section-title">Wanneer heb je versterking nodig?</h2><p className="section-lead">Een vacature, uitval of verandering kan om andere ervaring vragen. Deze situaties helpen om jouw vraag concreet te maken.</p><div className="situation-list mt-7">{page.situations.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
    <Section><p className="eyebrow">Concrete rollen</p><h2 className="section-title">Functies waarvoor we zoeken</h2><p className="section-lead">De functietitel is een begin. We bespreken ook het takenpakket, de verantwoordelijkheden en de samenwerking, zodat duidelijk is wie het werk moet oppakken.</p><div className="role-directory mt-7">{page.roles.map(([title,text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><a className="inline-flex font-bold text-accent mt-7" href="/professionals">Bekijk ons netwerk</a></Section>
    <StatementSection eyebrow="Onze zoektocht" title={page.searchHeading} dark={sector === 'projecten'}><p>{page.searchText}</p><p>Je krijgt een voorstel voor de aanpak en vergoeding voordat we starten. We spreken af hoe we terugkoppelen en gebruiken reacties uit de markt om het profiel waar nodig verder aan te scherpen.</p></StatementSection>
    <EditorialSection eyebrow="Vast of tijdelijk" title="Een vaste collega of tijdelijke inzet" tone="white"><p>Voor een vaste collega zoeken we via werving & selectie. Bij tijdelijke versterking bespreken we detachering of interim. Detavast kan passen als een professional eerst via Wedeploy start en later bij jouw organisatie in dienst komt.</p><p>We kiezen de inzetvorm aan de hand van de werkzaamheden, de gewenste periode en de samenwerking. Beschikbaarheid, voorwaarden en verantwoordelijkheden stemmen we vooraf af. Wedeploy is gevestigd in Amsterdam en werkt landelijk.</p><div className="text-link-list"><a href="/werving-selectie">Werving & selectie</a><a href="/detachering">Detachering & detavast</a><a href="/interim-zzp">Interim & zzp-bemiddeling</a></div></EditorialSection>
    <FAQ items={[...page.faq]} /><ClosingCTA title="Wie heeft jouw team nodig?" text="Vertel over het werk, de gewenste start en de ervaring die je zoekt. We bespreken samen het profiel en de aanpak." label="Bespreek jouw personeelsvraag" href={query} />
  </PageLayout>;
}
